### ISSUE TITLE
Remove 'R' Dependency ( and therefore DESeq )

### ISSUE THREAD

**Issue by molikd** [mhammell-laboratory/TEtranscripts#1]
This is a feature request for removing the DESeq R dependency in TEToolkit, this essentially means having to write the DESeq functions of newCountDataSet (not essential), estimateSizeFactors, estimateDispersions and nbinomTest. 

There are four places where R is called from TEToolkit:
- [TETranscripts-> R Call](../blob/master/bin/TEtranscripts#L599-679)
- [TEPeaks-> R Call 1](../blob/master/bin/TEpeaks#L627-677)
- [TEPeaks-> R Call 2](../blob/master/bin/TEpeaks#L680-714)
- [Normalization.py-> R Call](../blob/master/TEToolkit/Normalization.py#L77-108)

**Comment by status-five** [comment]
Looked at:

https://bioconductor.org/packages/release/bioc/manuals/DESeq/man/DESeq.pdf 

**From Page 21**: newCountDataSet—This function creates a CountDataSet object from a matrix or data frame of count data

**From Page 9**: estimateSizeFactors—Estimate the size factors for a CountDataSet

**From Page 6**: estimateDispersions—This function obtains dispersion estimates for a count data set.  For each condition (or collectively for all conditions, see ’method’ argument below) it first computes for each gene an empirical dispersion value (a.k.a.  a raw SCV value), then fits by regression a dispersion-mean relationship and finally chooses for each gene a dispersion parameter that will be used in subsequent tests from the empirical and the fitted value according to the ’sharingMode’ argument.

**From Page 18**: nbinomTest—This function tests for differences between the base means of two conditions (i.e., for differential expression in the case of RNA-Seq).

**Comment by status-five** [comment]
for estimateDispersions we use the blind, per-condition, and pooled methods, however we don't use pooled-CR.  The R code generates TEtranscripts_out_gene_TE_analysis.txt and TEtranscripts_out_sigdiff_gene_TE.txt files for TETranscripts. It looks like TEPeaks is similar. The  the R code, basically, is running some Stats/Diff/Normalization, then its outputting into a file. It looks like then we might be best served by two sets of functions for this: replacements for estimateSizeFactors, estimateDispersions, and nbinomTest; and replacements for outputting the data into the graphs/tables its creating.

**Comment by status-five** [comment]
I'm going to write this on a fork: https://github.com/status-five/tetoolkit

**Comment by emattei** [comment]
I totally support this, I am just interested in getting raw counts out of the tool and it would be amazing not have to deal with R and DESeq dependencies.

**Comment by olivertam** [comment]
Hi. 

If you only want the raw counts, you can use [`TEcount`](https://github.com/mhammell-laboratory/TEtranscripts#tecount) in the `TEtranscripts` package. This performs only the quantification, and thus does not require R or DESeq2.

Thanks.

**Comment by emattei** [comment]
Oh I see, I completely missed the existence of TEcount tool. Sorry about that. TEcount is exactly what I was looking for!
