### ISSUE TITLE
source of Z. maize TE annotation

### ISSUE THREAD

**Issue by kcamnairb** [mhammell-laboratory/TEtranscripts#100]
Hi, I've been using the maize TE annotation available here, [http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/ZmAGPv4_TE.gtf.gz](url), and I was wondering if you could tell me how this was generated. I know you formatted it for TEtranscipts, but is the original from MaizeGDB or did you produce this yourself?

Thanks,
Brian

**Comment by olivertam** [comment]
Hi Brian,

Thank you for your interest in the software.
Yes, the original annotation is obtained from [MaizeGDB](https://download.maizegdb.org/Zm-B73-REFERENCE-GRAMENE-4.0/Zm-B73-REFERENCE-GRAMENE-4.0.TEs.1.0.gff3.gz), which (as you correctly pointed out) was then formatted for TEtranscripts.

Thanks.

**Comment by kcamnairb** [comment]
Oliver, great thank you.
