### ISSUE TITLE
TEcount processes multiple bam files at the same time

### ISSUE THREAD

**Issue by shijiu001** [mhammell-laboratory/TEtranscripts#104]
Hello, thank you for providing such a useful TE analysis tool.
I would like to ask if TEcount can only handle one bam file at a time, or can it handle multiple bam files at the same time as TEtranscripts does? Maybe output a table containing the representation of each TE in each sample.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software. The rationale behind TEcount was to be able to parallelize the processing of BAM files, so you can run multiple TEcount at the same time.
What we do to create the table that you describe (and one that TEtranscripts generates), is just to combine the TEcount output tables using Unix `join` (or other similar approaches), using the feature name as the key.

Thanks.
