### ISSUE TITLE
Intergenic TEs

### ISSUE THREAD

**Issue by tiplud** [mhammell-laboratory/TEtranscripts#106]
Hi!
  Thank you for this excellent package. I am using TEcount to quantify gene and TE expression in mouse samples. I obtained the TE gtf file (GRCm38_GENCODE_rmsk_TE.gtf) from http://hammelllab.labsites.cshl.edu/software/#TEtranscripts
My understanding is that the TEs are intergenic or intronic ? If so, is there a way to only consider intergenic TEs ?

Thank you very much,
Debayan

**Comment by tiplud** [comment]
Hi Oliver,
    Thank you so much for the prompt reply! So, just to verify, I should remove repeatmasker TE coordinates which fall in exon/intronic locations, and then run the quantification again with the reduced TE gtf, right?

Thanks again,
Debayan

**Comment by olivertam** [comment]
Hi Debayan,

If you are only interested in intergenic TE (and want to ignore reads unambiguously from exonic and intronic TE), then your approach is correct (replacing the original TE GTF with the reduced TE GTF). Please note that this approach does not eliminate the possibility of an exonic/intronic TE read being assigned to an intergenic one if the read can still aligns to the intergenic TE.

Thanks.

**Comment by tiplud** [comment]
Hi Oliver,
   Thanks a lot for your quick explanations!
Best,
Debayan
