### ISSUE TITLE
requires argparse, a defunct library

### ISSUE THREAD

**Issue by Apteryks** [mhammell-laboratory/TEtranscripts#111]
Hi,

The project requires argparse, whose author apparently declared it unmaintained and archived the repository (see: https://github.com/ThomasWaldmann/argparse/).

Is this a Python 2 specific dependency?  If so, it could be specified as such in the setup.py.  Thanks!

**Comment by olivertam** [comment]
Thank you for letting us know.
Yes, it was included to maintain Python 2 compatibility. We will update the requirements as it is now in the standard libraries.

Thanks.
