### ISSUE TITLE
Feature request: specify output directory

### ISSUE THREAD

**Issue by niekwit** [mhammell-laboratory/TEtranscripts#117]
Hello, really like your TE tool! I would like to request a feature: would it be possible to introduce an option to specify the output directory rather than using the current directory?
Thank you very much,

Niek

**Comment by olivertam** [comment]
Hi Niek,

Sorry for the slow response. We'll take a look and see if how complicated it would be.

Thanks.

**Comment by olivertam** [comment]
Hi Niek,

We added the `--outdir` parameter to allow you to specify the output directory. However, that directory will have to already exist, or the program will exist.

Thanks.

**Comment by niekwit** [comment]
Hi Oliver, thanks so much for implementing this, really appreciated.
