### ISSUE TITLE
Generate pre-built index

### ISSUE THREAD

**Issue by zhangaicen** [mhammell-laboratory/TEtranscripts#118]
Hi Oliver, 
    I have a TE.bed for rice genome which is newly annotated by myself, could you please help to generate pre-built index pre-built index for TEtranscripts and the pre-built index for TElocal? Thanks very much
[rice7.0_TElib.bed.gz](https://github.com/mhammell-laboratory/TEtranscripts/files/9388361/rice7.0_TElib.bed.gz)
.

**Comment by olivertam** [comment]
Hi,

We will try to generate the indices for you. Once they are ready, they will be available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/private/zhangaicen/).

Thanks.
