### ISSUE TITLE
Singularity container derived from docker container misses DESeq2 

### ISSUE THREAD

**Issue by Rhinogradentia** [mhammell-laboratory/TEtranscripts#120]
HI,

I'm trying to run tetranscripts from a singularity container which was build from your docker container like it is documented in your README.rst (https://github.com/mhammell-laboratory/TEtranscripts/blob/master/README.rst#alternative-singularity-installation-for-hpc). I pulled the latest docker Image yesterday. 
```
 singularity pull tetranscripts.sif docker://mhammelllab/tetranscripts:latest
```
Singularity Version:
```
$ singularity --version
singularity version 3.8.7-1.el7
```
Following Error is thrown:
```
[...]
In library ../bam_aligned/3.markdup.sorted.bam: 
Total annotated reads = 1190286 
Total non-uniquely mapped reads = 1428031 
Total unannotated reads = 9901076 

INFO  @ Wed, 31 Aug 2022 19:57:18: Finished processing sample files 
INFO  @ Wed, 31 Aug 2022 19:57:18: Generating counts table 
INFO  @ Wed, 31 Aug 2022 19:57:18: Performing differential analysis ...
 
Error in library(DESeq2) : there is no package called ‘DESeq2’
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
INFO  @ Wed, 31 Aug 2022 19:57:19: Done 
```
I call it this way:
```
singularity exec tetranscripts.sif TEtranscripts \
   -c ../bam_aligned/1.markdup.sorted.bam ../bam_aligned/2.markdup.sorted.bam ../bam_aligned/3.markdup.sorted.bam   \
   -t ../bam_aligned/4.markdup.sorted.bam ../bam_aligned/5.markdup.sorted.bam ../bam_aligned/6.markdup.sorted.bam  \
   --TE GRCh38_Ensembl_rmsk_TE.gtf  \
   --GTF GRCh38_GENCODE_rmsk_TE.gtf \
   --sortByPos --mode multi 
```

First I tried to build my own singularity container using conda. There the same error occurred despite the fact that I also installed R and Bioconductor libraries. I also tried to use DESeq instead of DESeq2, but it throws the same error.

Any help would be greatly appreciated.

Best,
Nadine

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
I've contacted my colleague who worked on the Singularity module, who might have more insights.
It might also be related to something that I [found online](https://stackoverflow.com/questions/67377646/error-when-running-singularity-container-for-r-script).

Thank you for your patience.

**Comment by Rhinogradentia** [comment]
Hi,

thank you for forwarding this - I will wait. 
Honestly, I don't think it has something to do with your link as it is based on your docker container - I didn't change anything.  Alternatively, maybe I'm missing something regarding the requirements for the environment in which the docker container can be run.

Best,
Nadine

**Comment by olivertam** [comment]
Hi,

From @molikd:
> There was a silent error and DESeq2 didn't install correctly in the container. I'm working on a fix, locfit library seems to be the issue.

Thank you for your patience.

**Comment by molikd** [comment]
Pull request #121 should fix this error. It was caused by the package locfit.

**Comment by Rhinogradentia** [comment]
Thank you a lot - I will try it.
Will you update the docker container as well?
Best,
Nadine

**Comment by olivertam** [comment]
Hi,

The docker container has been updated.

Thanks.

**Comment by Rhinogradentia** [comment]
It worked just fine now - thank you again!
