### ISSUE TITLE
TEtoolkit

### ISSUE THREAD

**Issue by DanielaMombach** [mhammell-laboratory/TEtranscripts#123]
Hi, I am trying to run TEtranscripts and got this error in return. Have you seen this before?
```

File "/mnt/d/TEtranscripts-2.2.3/bin/TEtranscripts", line 32, in <module>
    from TEToolkit.IO.ReadInputs import read_opts2
ImportError: No module named TEToolkit.IO.ReadInputs
```
Thank you in advance,
Daniela

**Comment by olivertam** [comment]
Hi Daniela,

How did you install `TEtranscripts`? And what is your command line?

Thanks.

**Comment by DanielaMombach** [comment]
Yes, I installed v 2.2.3. My command line is:
 `/mnt/d/TEtranscripts-2.2.3/bin/TEtranscripts --format BAM --mode multi -t /mnt/d/srr_cispla/bam/SRR14310043.fastq_Aligned.out.bam /mnt/d/srr_cispla/bam/SRR14310044.fastq_Aligned.out.bam /mnt/d/srr_cispla/bam/SRR14310045.fastq_Aligned.out.bam -c /mnt/d/srr_cispla/bam/SRR14310037.fastq_Aligned.out.bam /mnt/d/srr_cispla/bam/SRR14310038.fastq_Aligned.out.bam /mnt/d/srr_cispla/bam/SRR14310039.fastq_Aligned.out.bam`

**Comment by DanielaMombach** [comment]
From this website https://pypi.org/project/TEtranscripts/#files.

**Comment by DanielaMombach** [comment]
I tried following the instructions and this is what appeared
```
python setup.py install --prefix /mnt/d/
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```
Thank you again,

**Comment by DanielaMombach** [comment]
I think I was able to fix it, thank you for your fast response!

**Comment by olivertam** [comment]
No problem. Let me know if you encounter more issues.

**Comment by DanielaMombach** [comment]
Actually I dowloaded again and followed the instructions thinking it would fix it, but the same error persisted.
```
/mnt/d/TEtranscripts-2.2.3/bin/TEtranscripts --format BAM --mode multi -t /mnt/d/srr_cispla/bam/SRR14310043.fastq_Aligned.out.bam /mnt/d/srr_cispla/bam/SRR14310044.fastq_Aligned.out.bam /mnt/d/srr_cispla/bam/SRR14310045.fastq_Aligned.out.bam -c /mnt/d/srr_cispla/bam/SRR14310037.fastq_Aligned.out.bam /mnt/d/srr_cispla/bam/SRR14310038.fastq_Aligned.out.bam /mnt/d/srr_cispla/bam/SRR14310039.fastq_Aligned.out.bam
Traceback (most recent call last):
File "/mnt/d/TEtranscripts-2.2.3/bin/TEtranscripts", line 32, in <module>
    from TEToolkit.IO.ReadInputs import read_opts2
ImportError: No module named TEToolkit.IO.ReadInputs
```

**Comment by DanielaMombach** [comment]
It appears to have installed successfully
```
Installed /mnt/d/lib/python3.8/site-packages/TEtranscripts-2.2.3-py3.8.egg
Processing dependencies for TEtranscripts==2.2.3
Searching for pysam==0.15.4
Best match: pysam 0.15.4

Using /usr/lib/python3/dist-packages
Finished processing dependencies for TEtranscripts==2.2.3
```

**Comment by olivertam** [comment]
No worries.
Might I suggest the following if you haven't already done this:
```
$ export PYTHONPATH="/mnt/d/lib/python3.8/site-packages/:$PYTHONPATH"
```
This will point `python` to the location of the `TEtranscripts` installation.
You could either put it in your `.bashrc` (or `.zshrc` depending on your shell) to have it activated by default, or just run that command before you use `TEtranscripts`.

Let me know if you still have issues.

Thanks.
