### ISSUE TITLE
outSAMmultNmax

### ISSUE THREAD

**Issue by imerelli** [mhammell-laboratory/TEtranscripts#125]
Hi, I'm wondering if setting the  --outSAMmultNmax parameter of STAR can impact the analysis (while the parameters 
 --winAnchorMultimapNmax and --outFilterMultimapNmax are discussed, there is no information about --outSAMmultNmax).

**Comment by olivertam** [comment]
Hi,

`--outSAMmultNmax` dictates how many alignments outputted to SAM/BAM after running STAR. By default, it is set to `-1`, which means output all alignments found. Setting this would simply restrict the number of alignments that are reported ( the total number of alignments found will still be indicated in the `NH:i:` tag), and thuscould remove alignments that were found and required for accurate quantification.

Thus we recommend leaving it at the default value.

Thanks
