### ISSUE TITLE
T2T_refGene.gtf & T2T_rmsk_TE.gtf

### ISSUE THREAD

**Issue by heeralvi** [mhammell-laboratory/TEtranscripts#126]
Hi Team,

Thanks for developing this wonderful tool, i am working RNA seq data using T2T as a reference (https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz). I have been trying to make gene reference and repeat masker file but i am getting an error in gtf format. I was wondering if you can help me to get these reference file, that would be very helpful.

Thanks

**Comment by olivertam** [comment]
Hi,

You can try to get the RefSeq gene annotations (as GTF) from [UCSC Table Browser](http://genome.ucsc.edu/cgi-bin/hgTables?hgsid=1483457127_MZgoQ0nuQatG6LA2dgE1TZW9mUTi&clade=hub_3671779&org=hub_3671779_Human&db=hub_3671779_hs1&hgta_group=genes&hgta_track=hub_3671779_refSeqComposite&hgta_table=0&hgta_regionType=genome&position=chr9%3A145%2C458%2C455-145%2C495%2C201&hgta_outputType=primaryTable&hgta_outFileName=). I think it should work without any modifications (just make sure the chromosome names matches your FASTA file (i.e. your FASTA file starts with "chr").
For the TE annotation, you can download the GTF [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/T2T_CHM13_v2_rmsk_TE.gtf.gz).
Let us know if you are still encountering issues.

Thanks

**Comment by heeralvi** [comment]
Hi Oliver,

That was very helpful, solved the problem, Thanks a lot.
