### ISSUE TITLE
Generating pre-built gene and TE indexes for TEcount with TEtranscripts_indexer

### ISSUE THREAD

**Issue by samuelruizperez** [mhammell-laboratory/TEtranscripts#127]
Hi:

Thank you for developing this wonderful tool. 

I was wondering if using this version of [TEtranscripts_indexer.gz](https://github.com/mhammell-laboratory/TEtranscripts/files/6118032/TEtranscripts_indexer.gz) is still the way to go if I wish to generate pre-built gene and TE indexes and avoid re-building them every time I run TEcount. I need to run TEcount with several BAMs and it would be nice and really time-saving to use the same pre-built indexes for all.

Thank you,
Samuel

**Comment by olivertam** [comment]
Hi,

Sorry for the slow response.
Yes, you can use the indexer in your link to generate the pre-built gene & TE indices.

Thanks.

**Comment by samuelruizperez** [comment]
Thanks for the clarification! I've generated the indexes and everything is running fine so far.

Thank you,
Samuel
