### ISSUE TITLE
gtf used to generate pre-built index?

### ISSUE THREAD

**Issue by EmersonH2** [mhammell-laboratory/TEtranscripts#131]
Hello,

Would it be possible for you to share the original .gtf you used to generate the pre-built index (https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/hg38_rmsk_TE.gtf.locInd.gz)? I assume it was one of these from the RepeatMasker website--which one?
![Screen Shot 2023-01-16 at 1 39 56 PM](https://user-images.githubusercontent.com/60073915/212746708-716614e9-bb6b-4f0f-b6b2-89f52518eff6.png)

Thank you so much for your help!
Emerson

**Comment by olivertam** [comment]
Hi Emerson,

Thank you for your interest in the software.
The original GTF used for the prebuilt index is available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/hg38_rmsk_TE.gtf.gz). It is derived from the UCSC repeatMasker output for the hg38 genome.
I also want to check whether you are using `TElocal` or `TEtranscripts` for your analysis. The prebuilt indices for the two software are not compatible. The one that you linked in your original post is for `TElocal`, while the `TEtranscripts` prebuilt index for hg38 is available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/prebuilt_indices/hg38_rmsk_TE.gtf.ind.gz)

Thanks.

**Comment by EmersonH2** [comment]
Thank you so much, Oliver! Yes, I'm working with `Telocal`--thank you for checking!
