### ISSUE TITLE
TEcount on multple BAMs

### ISSUE THREAD

**Issue by cottrellka** [mhammell-laboratory/TEtranscripts#132]
My experiment involves a more complicated design than treatment and control, so running TEtranscripts isn't the best option. I would prefer to get a count file for each BAM, or ideally one file with all of the counts, and then perform the DESeq2 analysis separately so I have more control over the analysis design. Does TEcount support multiple BAM files, or do you have a suggested work around? Thanks.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software, and sorry for the slow response.
We would recommend using TEcount for each BAM, and then combine the output (count files) into a single file, and then perform DESeq2 independently.

Thanks.
