### ISSUE TITLE
TEcount:287 error

### ISSUE THREAD

**Issue by dmnburrows** [mhammell-laboratory/TEtranscripts#137]
Hi there, I'm having an issue with running Te counts. 

Here is the code I am running:
TEcount --sortByPos --format BAM --mode multi -b /cndd3/dburrows/DATA/te/rna/aligned.subset/1241-GABA.plus.ss_filt.bam --GTF /cndd3/dburrows/DATA/te/gtf/annotations/gencode/gencode.v37.annotation.hg38.gtf --TE /cndd3/dburrows/DATA/te/gtf/annotations/rmsk/rmsk.hg38.gtf --project 1241-GABA.plus.ss_filt --outdir /cndd3/dburrows/DATA/te/rna/tet_counts.subset/

And here is the error:

![Screenshot 2023-04-28 at 19 31 50](https://user-images.githubusercontent.com/45342427/235279627-e93e874b-fdcd-4e53-b04f-ae26a851b2b2.png)

I'm pretty sure that the could not retrieve index is a warning and can be ignored, I've run into it in the past and the programme still runs to completion. But the subsequent errors I have not seen before and terminate the programme. As far as I am aware my bam file is sorted by coordinates and I provided the --sortByPos input, here is my bam header in case theres something off with it:

![Screenshot 2023-04-28 at 19 34 51](https://user-images.githubusercontent.com/45342427/235279682-35d949ce-4f00-48c8-a8cb-f6064adbdb66.png)

Something that might be an issue, is how I have processd the bam file. I have removed certain reads, and this is paired-end data so there are definitely some reads in the bam file whose paired mate are not present. I'm not sure if that would cause this issue? If not any other ideas about the problem would be much appreciated! I have run TE counts successfully previously on the same GTF and TE gtf files, so the only thing different is the BAM file in this case. 

Thanks so much for the great work.

**Comment by olivertam** [comment]
Hi,

Unfortunately, you have identified the cause of the error. For paired end data, the program does expect the paired mate to be present, so any unpaired reads will throw an error. If you are removing certain reads, you will have to remove its corresponding pair as well.

Thanks.

**Comment by dmnburrows** [comment]
Ah that makes sense! Thanks for your speed response.
