### ISSUE TITLE
Pre-generated TE GTF for GRCm39 Ensembl assembly

### ISSUE THREAD

**Issue by kcwum** [mhammell-laboratory/TEtranscripts#138]
Hi team - I see GRCm38_Ensembl_rmsk_TE.gtf but not an equivalent file for GRCm39. I do see mm10 or mm39_rmsk_TE.gtf. Can you please advise which TE GTF file I should use for data aligned to GRCm39 Ensembl assembly. Thank you!

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
The TE GTF file for GRCm39 Ensembl assembly is now available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/GRCm39_Ensembl_rmsk_TE.gtf.gz).
Please let us know if you encounter any issues.

Thanks

**Comment by olivertam** [comment]
Hi,

Please check the `TE_GTF` folder [here](https://www.dropbox.com/scl/fo/jdpgn6fl8ngd3th3zebap/ALDQ94uFrf3r1QM1zoT9jHU/TEtranscripts?dl=0&rlkey=41oz6ppggy82uha5i3yo1rnlx&subfolder_nav_tracking=1).

Thanks.
