### ISSUE TITLE
Error in building TE index with my TE.gtf file

### ISSUE THREAD

**Issue by biomesser** [mhammell-laboratory/TEtranscripts#140]
Hello!
I created TE.gtf file for use with TEtranscripts.
I get error "Error in building TE index "

Please, check my TE.gtf
What is wrong in my annotations?

Thanks!!
[sltk_bed_mod.gtf.zip](https://github.com/mhammell-laboratory/TEtranscripts/files/11651597/sltk_bed_mod.gtf.zip)

**Comment by biomesser** [comment]
Hl, Olivertam!!
Thanks for you ansver! Now my TE.gtf is valid.

Also, let me ask please:
I used TAIR10TE.gtf from https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/TAIR10_TE.gtf.gz.
My .bam files have high expressions of AT3G32415, but TE expression counting not found this TE.
What could be the reason?

**Comment by olivertam** [comment]
Hi,

If you look up AT3G32415 on [Arabidopsis.org](https://www.arabidopsis.org/servlets/TairObject?type=locus&id=227313), you would find that it's associated with the TE, [AT3TE54550](https://www.arabidopsis.org/servlets/TairObject?type=transposon&id=2177). That might be the entry that you need to look at in the TE output file, as the TAIR10 TE annotations follow the ATxTExxxxx rather than the gene annotation (ATxGxxxxx).

Thanks.

**Comment by olivertam** [comment]
Hi,

Sorry, now I understand.
TEtranscripts aggregate TE counts by element type (e.g. subfamily). Thus, AT3TE54550 is aggregated into ATCOPIA78. The ATxTE ID is for each copy, which is used for initial quantification, but then aggregated by the sub-family (`gene_id`)

Thanks.

Thanks.

**Comment by biomesser** [comment]
Thanks for you ansvers!!!
That is my output file. It contein the ATCOPIA78.
[biomesser_TE_GTF_FROM_TEtran.cntTable.zip](https://github.com/mhammell-laboratory/TEtranscripts/files/11664036/biomesser_TE_GTF_FROM_TEtran.cntTable.zip)

**Comment by olivertam** [comment]
Hi,

The results you saw for AT3G32415 is probably described on this line:
```
gene/TE Heat_16_h_161   Heat_16_h_162   Wt_1    Wt_2
ATCOPIA78:Copia:LTR  451253  395844  205     834
```

Thanks.

**Comment by biomesser** [comment]
Yes, i understand it!!
Thanks very match!

**Comment by biomesser** [comment]
Hi Oliver!!

May I please ask how TEtranscripts compares id AT3G32415 with id AT3TE54550 and with gene_id/family_id ?
Where can i get the table file with this information?

Thanks!!

**Comment by olivertam** [comment]
Hi,

Actually, that information is from TAIR (see [here](https://www.arabidopsis.org/servlets/TairObject?type=locus&id=227313) for an example). 
If you need to match gene ID with TE, you can look at [this file](https://www.arabidopsis.org/download_files/Genes/TAIR10_genome_release/TAIR10_gff3/TAIR10_GFF3_genes_transposons.gff), and look for lines that has the following:
```
Note=transposable_element_gene
```
You can then look up the TE sub family in [this file](https://www.arabidopsis.org/download_files/Genes/TAIR10_genome_release/TAIR10_transposable_elements/TAIR10_Transposable_Elements.txt) to see which TE subfamily it is.

Thanks.

**Comment by biomesser** [comment]
> Hi,
> 
> The results you saw for AT3G32415 is probably described on this line:
> 
> ```
> gene/TE Heat_16_h_161   Heat_16_h_162   Wt_1    Wt_2
> ATCOPIA78:Copia:LTR  451253  395844  205     834
> ```
> 
> Thanks.

Hi!
I would like to report a possible error in your answer. When using your file.gtf , the program works without error messages. But the resulting file has zeros for all mobile elements.
I corrected the column with the chromosome in your  file.gtf (leaving only the number, removing the "Chr"). After that, the program correctly annotates mobile elements.
I decided to write about it just in case for other readers and users.

Thanks!

**Comment by biomesser** [comment]
I would like to ask, how much does it matter which files are specified as control (with the -c option) and experience (with the -t option)?
As I understand it, this is of fundamental importance only for data processing using DESeq2.

**Comment by olivertam** [comment]
> > Hi,
> > The results you saw for AT3G32415 is probably described on this line:
> > ```
> > gene/TE Heat_16_h_161   Heat_16_h_162   Wt_1    Wt_2
> > ATCOPIA78:Copia:LTR  451253  395844  205     834
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks.
> 
> Hi! I would like to report a possible error in your answer. When using your file.gtf , the program works without error messages. But the resulting file has zeros for all mobile elements. I corrected the column with the chromosome in your file.gtf (leaving only the number, removing the "Chr"). After that, the program correctly annotates mobile elements. I decided to write about it just in case for other readers and users.
> 
> Thanks!

Hi,

Thanks for your feedback. Yes, mismatch between chromosome names is a major reason why there might be zero counts for all TE/genes. Your fix of correcting the GTF is the right approach.

Thanks.

**Comment by olivertam** [comment]
> I would like to ask, how much does it matter which files are specified as control (with the -c option) and experience (with the -t option)? As I understand it, this is of fundamental importance only for data processing using DESeq2.

Hi,

You are correct that the importance of `-c` and `-t` applies only the differential analysis (e.g. `DESeq2`). In that case, the libraries in `-c` are used as the "reference" for the `-t` to compare against. Thus, values such as log2 fold change are calculated as `log2(treatment value / control value)`. Thus the libraries used for each one would change the sign (i.e. directionality) of the value.

Thanks
