### ISSUE TITLE
single cell RNA-seq

### ISSUE THREAD

**Issue by zhongguozhiwang** [mhammell-laboratory/TEtranscripts#148]
Hi,
Thanks to the author for developing such a great tool. I want to analyze transposons in single-cell transcriptome data. Is this tool suitable for single-cell transcriptome data?
Thank you!

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
Unfortunately, `TEtranscripts` cannot handle single-cell datasets, as it lacks the ability to work with cell barcode and UMI.
A software that could handle single-cell data is currently in development.

Thanks.
