### ISSUE TITLE
half of the reads are not annotated 

### ISSUE THREAD

**Issue by MonkeySylvia** [mhammell-laboratory/TEtranscripts#155]
Hi,
I'm using TEtranscript to count gene/TE expression from human samples, everything ran smoothly but there are ~40% unannotated reads reported by TEtranscript. I didnt get any error messages so I cound't figure out why this is the case.

Using STAR for my mapping (Ensemble gtf file):
```
       STAR \
      --runMode alignReads \
      --genomeDir $INDEX \
      --readFilesIn $f1 $f2 \
      --runThreadN 100 \
      --sjdbGTFfile Homo_sapiens.GRCh38.110_chr.gtf \
      --outSAMtype BAM SortedByCoordinate \
      --outFilterMultimapNmax 100 \
      --alignIntronMax 1000000 \
      --outSAMmultNmax 1 \
```

Then TE transcript
```
TEtranscripts \
-t sample1.bam sample2.bam sample3.bam \
-c sample4.bam sample5.bam  sample6.bam \
--sortByPos \
--GTF Homo_sapiens.GRCh38.110_chr.gtf \
--TE GRCh38_Ensembl_rmsk_TE_chr.gtf \
--mode multi \
--stranded reverse &
```

and here is the output
```
In library sample1.bam:
Total annotated reads = 35048548
Total non-uniquely mapped reads = 1
Total unannotated reads = 21057084

```

I did check the NH flag in my bam file, and there are definitely reads with NH:20, NH:5 in there.
Thank you!

**Comment by olivertam** [comment]
Hi,

Unannotated reads are not necessarily unusual. These could be intronic reads (which are ignored by default), basal transcription of the genome, or other reads derived from features that are not annotated by Ensembl (as a gene) or as a TE (some examples could be tRNA, ribosomal RNA, some mitochondrial genes).

However, I am quite surprised to see that `Total non-uniquely mapped reads = 1`, which is very unusual. Is it just for one library, or all of them?

Thanks.

**Comment by MonkeySylvia** [comment]
Hi Oliver,

Thanks for replying! Each library should at least have more than 20% multi-mapping reads (from my STAR ouput). The TEtranscript outputs are similar across my samples, which have very low non-unique mapping reads. Do you have any ideas why this is the case? I wonder if I should re-map my reads using hisat2 or bowtie2.

**Comment by MonkeySylvia** [comment]
Got you!! I'll redo the mapping again. Thanks!
