### ISSUE TITLE
 The question about TE disturbing with gene expression

### ISSUE THREAD

**Issue by Wenwen012345** [mhammell-laboratory/TEtranscripts#158]
Hey @olivertam  oliver~

I have some questions here that I would like to ask you.  It is mainly about the interference of TE on gene expression.  I think the modes in which TE may interfere with genes on the genome may be as follows: 

1.  Inserted in the promoter part,  and methylation inhibits the binding of transcription factors; 
2.  Inserted in the transcripts start site （TSS）, forming a strong interference; 
3.  Inserting in the exon part is also a strong interference; 
4.  Inserting only in the intron part is only a weak interference. 
 Which kind of interference do you think is the main effect?

 I am studying something about pathways and the interference of transposons in pathways on some genes.  After using EDTA to discover some fragmented transposons, we found that there are transposons present in the TSS of the gene (such as the figure below), and it happens that this gene is basically not expressed.  I think a transposon inserted at the start codon would strongly interfere with gene expression, right?

![image](https://github.com/mhammell-laboratory/TEtranscripts/assets/63379795/9573fe30-566e-44e2-a1b9-a27a5a5125d3)

Appreciate your possible answers!
Wen

**Comment by olivertam** [comment]
Hi,

It's very difficult to assess the extent of interference, but you're probably right that TE insertions in the promoter and/or start codon could have a significant impact on gene expression (though it's unclear what the exact impact might be, as there are examples of "activating", "suppressing" and "temporally altering" in the literature). Of course, this also depends on the "age" of the insertion, as older insertional events might have "co-evolved" with the nearby gene to have it not be deleterious to the organism. 

While exonic and intronic insertions are less likely to directly impact the canonical transcriptional initiation of the gene (though if they could if they land in enhancer regions), they could still impact gene expression by altering the splicing profile, thus leading to potential nonsense-mediated decay (and thus reduced expression). They could also drive the expression of "TE-initiated" alternate transcripts, which could have a dominant negative effect on the gene product (e.g. in-trans repression if the self-regulatory region is erroneously over-expressed).

As such, it's hard to determine the "strongest" impact of TE insertion (especially if they have been adapted to/co-opted), as each insertion could have differing impact even if they occur in similar functional regions of the gene.

Hope this is somewhat helpful. Please let me know if anything is unclear.

Thanks.

**Comment by Wenwen012345** [comment]
Very useful, thank you very much~ Basically the complexity you stated is about as complex as I imagined, so I would like to pursue possible research strategies on this.

**Comment by Wenwen012345** [comment]
@olivertam 

In addition, I mainly want to know about methylation.  What do you think?  Because I combined HIFI sequencing.  HIFI&#39;s latest sequencing strategy allows us to analyze the methylation status on the sequence.  So I found that there were a number of low-expressed genes that seemed to be associated with methylation due to possible transposon insertions.  The locations of these methylations include the promoter part (will promoter methylation inhibit gene expression? ) and within the gene.  Two more obvious examples are given below.  How do you comment on this?

![image](https://github.com/mhammell-laboratory/TEtranscripts/assets/63379795/a7878b2f-fb78-42eb-9959-59875f06a70e)

**Comment by olivertam** [comment]
Hi,

You're probably right that promoter methylation is suppressing gene expression, though it's tough to say if the TE insertion is what drove the methylation, or if other factors (such as cell type / developmental stage) was the driver.

However, it should be noted that while the TE is heavily methylated, the pattern of methylation does not appear to "spread" the surrounding gene region. In fact, if you look at the methylation of promoters of these gees, while it's high, they are not showing consistently high levels to the nearby TE (in fact, they tend to peak at the promoter, rather than spreading from the TE). Thus, it could be argued that the methylation is not driven by spreading of TE-associated methylation, but a more gene-promoter-specific methylation.

Thanks.

**Comment by Wenwen012345** [comment]
Thank you very much for your constructive opinions ~ your opinions are really useful! I&#39;ll think about this and try to find some information.  You are really knowledgeable, thank you!
