### ISSUE TITLE
Extract specific type of Transposable Element (TE)reads 

### ISSUE THREAD

**Issue by sixingchen718** [mhammell-laboratory/TEtranscripts#162]
Hi Oiver,
Thank you to develop the powerful tool,I have a question,I currently have bam files that have been mapped using STAR for my research. I need to extract reads for a specific type of Transposable Element (TE). Can TEcount do this? Or can TEcount output bam files that are mapped to TEs?
Regards,
Fixing

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
TEcount is not designed to pull our reads, but you can use tools such as [bedtools intersect](https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html) to do so. You will need a BED or GTF with the TE of interest to intersect with your BAM file.
Please note that you may not get the exact number of reads corresponding to TEcount's output, as there is an EM step to re-destribute read that cannot be represented easily in a BAM file.

Thanks.

**Comment by sixingchen718** [comment]
Thank you for your guidance regarding the use of bedtools intersect for extracting reads related to transposable elements (TEs) from BAM files.I share your concerns about the potential accuracy issues when using bedtools intersect,I will proceed with using bedtools intersect as per your suggestion and compare the result of  TEcount. 
Thanks so much
