### ISSUE TITLE
The issue of slow running speed of TEtranscripts

### ISSUE THREAD

**Issue by cyyisbest** [mhammell-laboratory/TEtranscripts#163]
Thank you very much for developing this software. I encountered the following issue during the process of running. When I was annotating with TEtranscripts, the server was using a single thread, and it took three days to finish running. I want to ask if there are any actions that can speed up this process.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.

We would recommend running `TEcount` (included with TEtranscripts) on each sample for quantification as a means to parallelize the approach. You can then combine all the output count tables into a single combined count table, and then perform differential analysis with DESeq2.

Thanks.

**Comment by cyyisbest** [comment]
Thank you very much for your response.
