### ISSUE TITLE
mapping gtf version different with TEtranscripts version

### ISSUE THREAD

**Issue by songlyzz** [mhammell-laboratory/TEtranscripts#166]
Hi olivertam，
  I I'd like to ask for advice that I use gencode v25 gtf to map, the version is different with GRCh38_Ensembl_rmsk_TE.gtf. Will it still work well in different reference version?

Thanks,
Song

**Comment by olivertam** [comment]
Hi Song,

Thank you for your interest in the software.
I'm assuming you're using GENCODE FASTA for mapping, and the GENCODE v25 GTF for gene annotation.
I would recommend using [GRCh38_GENCODE_rmsk_TE.gtf](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/GRCh38_GENCODE_rmsk_TE.gtf.gz), which uses the same chromosome nomenclature as GENCODE.

Thanks.

**Comment by songlyzz** [comment]
Thank you very much!
