### ISSUE TITLE
TE annotation for Rabbit (oryCun2)

### ISSUE THREAD

**Issue by hiskobay** [mhammell-laboratory/TEtranscripts#174]
Hi team,
I am utilizing TEtranscripts (and TEcount), and it works well for both human and mouse datasets. Now, I am looking to apply it to Rabbit RNA-seq datasets. However, a TE_GTF file specific to rabbits (e.g., oryCun2) is not available in your web storage. Could you please guide me on how to prepare the GTF file for rabbits? Thank you.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
If you are using sequences obtained from UCSC (e.g. oryCun2), you should access the Table Browser and obtain the UCSC [rmsk table](https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=1865401812_DcwjypTZSKfiJ7zFvWwf2Oc2H46l). You can then use our [perl script](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/makeTEgtf.pl.gz) to generate the TE GTF file as follows:
```
$ perl makeTEgtf.pl -c 6 -s 7 -e 8 -o 10 -t 11 -f 13 -C 12 -S 2 -n UCSC_rmsk [RMSK table] > [TE GTF]
```
We have generated a version of the [oryCun2 TE GTF](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/oryCun2_rmsk_TE.gtf.gz) that you can try to see if it works.

Thanks.

**Comment by hiskobay** [comment]
Sorry for my late reply.
The TEcount worked well with the rabbit GTF file you provided.
Thanks!
