### ISSUE TITLE
TE subfamily TPM nomalize

### ISSUE THREAD

**Issue by songlyzz** [mhammell-laboratory/TEtranscripts#176]
Hi olivertam：
  I am using TEcount to count TE subfamily from mus datas, and I confused if I want to look a single TE subfamily counts how can we nomalize the counts matrix to TPM matrix in subfamily level, can I just nomalize it from the length of TE subfamily or must from all solo length? And how to extract the more than 1000 subfamily length?
  Thanks very much!

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software. 

Unfortunately, it's non-trivial to calculate the TPM for TE. You will need to extract the length of each annotation matching the TE subfamily (indicated by the `gene_id` in the GTF file) and sum them to get the "length". 

We typically don't do this as we usually perform differential analysis using software (e.g. `DESeq2`) that prefers counts matrix, and then normalize using their approach (median of means in `DESeq2`'s case), and variance-stabilize transform the output for plotting (e.g. in a heatmap).

Thanks.
