### ISSUE TITLE
TElocal to locate the TE loci 

### ISSUE THREAD

**Issue by songlyzz** [mhammell-laboratory/TEtranscripts#177]
Hi olivertam,
  I sorry for bother you again, but I have trouble with TElocal and have to ask for your advice.
  When I use TElocal to find each TE loci, I was confused about the nomenclature for example: X6B_LINE_dup272:X6B_LINE:CR1:LINE, X6B_LINE_dup317:X6B_LINE:CR1:LINE, X6B_LINE_dup336:X6B_LINE:CR1:LINE ....
  Can I know it's real genome loci on the human genome? or how to disstinguish each TE loci?

Thanks very much!

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the `TElocal` software.
You can find the locations for the genomic loci [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/annotation_tables/). The GTF that were used to generate the `TElocal` indices are the same as the ones used in `TEtranscripts` (available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/), with the instance name in the `transcript_id` field.

Thanks.
