### ISSUE TITLE
[E::idx_find_and_load] Could not retrieve index file for '.1712579023.8525763.bam'

### ISSUE THREAD

**Issue by ptranvan** [mhammell-laboratory/TEtranscripts#185]
Hi,

Hi have this issue:

`[E::idx_find_and_load] Could not retrieve index file for '.1712579023.8525763.bam'
`
My command line is :

`singularity exec tetranscripts.sif TEtranscripts -t 1.bam 2.bam  -c 3.bam 4.bam --GTF Homo_sapiens-GCA_009914755.4-2022_07-genes.gtf --TE T2T-CHM13v2_rmsk_TE.nochr.centromere.gtf --stranded reverse --sortByPos --mode multi`

And I set 100GB of memory.

any solutions ?

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
If that is the only warning message, then there is no impact on your run (See also #82). This is an known issue with htslib throwing this warning despite not requiring the index. We hope to suppress this warning in future TEtranscripts releases.

Thanks.

**Comment by olivertam** [comment]
Hi,

Based on the message, it looks like you ran out of disk space:
```
samtools sort: failed writing to ".1712671194.444845.bam": No space left on device
```

**Comment by ptranvan** [comment]
That's strange because I have plenty of space.

I have ve set the `--outdir` parameter and for singularity the ` -W ` in the singularity exec command. 
Is there any default directory when I run the command I am not aware of ?

**Comment by olivertam** [comment]
Hi,

I'm afraid I have limited experience with Singularity. Are you running the singularity module in a different disk mount to your `-W` location (e.g. you're running Singularity on `$HOME`, but your data mount is elsewhere?
I'm also assuming you're using `-W` (workdir) and not `-w` (writable) by accident.
You can try this and see if the container is full (for some reason):
```
singularity exec -W [your workdir] tetranscripts.sif df
```
If so, maybe re-build the container (though I don't know why it would fill up unless it was made writable)
Sorry if this does not help.

Thanks

**Comment by ptranvan** [comment]
I have solved the issue.

I re-sorted my .bam manually using `samtools sort -n` 

and used TEtranscripts without `--sortByPos`

**Comment by olivertam** [comment]
Hi,

As mentioned above, this is an erroneous warning message from pysam that has no impact on the running of the software. You can ignore it 

Thanks

**Comment by xiatianjihao** [comment]
> Hi,
> 
> As mentioned above, this is an erroneous warning message from pysam that has no impact on the running of the software. You can ignore it
> 
> Thanks

Hi，

But my pipeline just exited directly without continuing, and there were no result files at all.
![QQ截图20241109212546](https://github.com/user-attachments/assets/bfee9900-73a5-4462-955c-23c194430e3b)

Thanks,

Xiaojuan

**Comment by olivertam** [comment]
Hi,

Is your library paired-end? If so, this is likely an error due to the presence of discordant or unpaired alignments in your BAM file. `STAR` typically do not output those, but if you're using something like `HISAT2`, you would need to set `--no-mixed` and `--no-discordant` parameters while aligning.

Let us know if that doesn't resolve the issue.

Thanks.

**Comment by xiatianjihao** [comment]
> > Hi,
> > Is your library paired-end? If so, this is likely an error due to the presence of discordant or unpaired alignments in your BAM file. `STAR` typically do not output those, but if you're using something like `HISAT2`, you would need to set `--no-mixed` and `--no-discordant` parameters while aligning.
> > Let us know if that doesn't resolve the issue.
> > Thanks.
> 
> Hi，
> 
> After I remapped my reads using Bowtie2, one of the samples processed successfully, but another one gave me an error. Could you help me check what might be the reason? Thank you very much!
> 
> ![QQ截图20241114153031](https://private-user-images.githubusercontent.com/26156228/386359239-81899ea0-66d8-495f-8e06-c0fbc345ae0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MTY1NjUsIm5iZiI6MTczMTYxNjI2NSwicGF0aCI6Ii8yNjE1NjIyOC8zODYzNTkyMzktODE4OTllYTAtNjZkOC00OTVmLThlMDYtYzBmYmMzNDVhZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDIwMzEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYjRlNWQ0MDUwYWRiMDZkNGJlMWE2YzJkYWMwZGVkNzMwZjQ0OWUyODc2ZmRkMDU2MzMxMWVmMWRmNTQzNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DD1spXR9MJMDmL2rv2ecFSB3b2b4JbqFPxKwop-FKlw)
> 
> Thanks,
> 
> Xiaojuan

Sorry, I got the where is the problem, I just used wrong file!

Best,

Xiaojuan

**Comment by xiatianjihao** [comment]
> Hi,
> 
> It looks like you're removing duplicates in your BAM file. This essentially removes all multi-mappers, and thus it negates the benefits of TEtranscripts to analyze repetitive sequences. It is recommended that you don't remove duplicates if you want to quantify TE, especially those with high similarity to consensus (and thus more likely to be identical across loci).
> 
> Thanks

Thank you so much!
