### ISSUE TITLE
Inquire about the suitability of TEtranscripts for long-read RNA-Seq analysis

### ISSUE THREAD

**Issue by evayfang2019** [mhammell-laboratory/TEtranscripts#187]
As a beginner in the field of bioinformatics, I am particularly interested in understanding how TEtranscripts performs in the context of long-read sequencing data analysis. Could you please provide insights into whether TEtranscripts is optimized for analyzing long-read RNA-Seq data? If not, I would greatly appreciate any recommendations you may have for alternative software tools that are tailored for such analyses.

**Comment by olivertam** [comment]
Hi,

TEtranscripts is not optimized for long-read RNA-seq data, and we would not recommend using it for that purpose. Our current opinion is that the standard long-read RNA-seq processing steps are not optimized to quantify transposable elements, and so it remains an unresolved issue. We are hoping to develop protocols and software that might address this in the future.

Thanks.
