### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by GimenaA** [mhammell-laboratory/TEtranscripts#191]
I'm encountering this issue when I tried running TEtranscripts. I've run TEtranscripts many times in the past.
**pkg_resources.DistributionNotFound: The 'TEtranscripts==2.2.1' distribution was not found and is required by the application**

**Comment by olivertam** [comment]
Hi,

Thank you for your question.
Did you (or your IT) upgrade/update your python recently? If there was a recent update (e.g. to a newer python version), then it might not know to look in the old version for the software.
You might have to reinstall it, but the changes from version 2.2.1 to version 2.2.3 (current) is relatively minor.
You can see the change details [here](https://github.com/mhammell-laboratory/TEtranscripts/releases).

Thanks
