### ISSUE TITLE
Upload the TE_GTF of Capra hircus

### ISSUE THREAD

**Issue by LindaMax001** [mhammell-laboratory/TEtranscripts#197]
Hi
    Thank you for developing the software.I built the TEgtf of Capra hircus using the file of makeTEgtf.pl.How can I upload the TEgtf of Capra hircus to the GTF you build (https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/)?
    Thanks

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software. We typically don't store TE GTF that others generate, but if you have no way of hosting it yourself, we could put it in our collection.
How big is the TE GTF after compression by gzip? If you could either put it in Dropbox/Google Drive/One Drive (or equivalent) and give us a link, we can transfer it to the relevant location.

Thanks.

**Comment by LindaMax001** [comment]
OK,the TE GTF after compression by gzip is only 1kb.I will put it on the Google Drive and give you the link,include the file of Capra_hircus_Ensembl_rmsk_TE.gtf.locInd and Capra_hircus_Ensembl_rmsk_TE.gtf.locInd.locations
