### ISSUE TITLE
Error: Hangup

### ISSUE THREAD

**Issue by dtx282000** [mhammell-laboratory/TEtranscripts#198]
Hi, I faced an error as follows:

<img width="698" alt="image" src="https://github.com/user-attachments/assets/b6bf7a09-d7aa-4bb0-9451-9e942f9e995e">

So, How I can solve it?

Best

Deng

**Comment by olivertam** [comment]
Hi,

Is the `Hangup` part of the error log, or are you indicating that it's taking a long time?
The `Could not retrieve` message is from `pysam`, and does not cause the software to fail.
It might just be taking time reading through the alignments.

Thanks.

**Comment by dtx282000** [comment]
HI,

Also, I can't understand how to deal with it.

Thanks

**Comment by olivertam** [comment]
Hi,

Is the job still running, or did it end (with an error)?
What is the command line you used?
Are you using a cluster, such as SLURM, where you need to specify the time the program requires?
As mentioned above, the pysam message does not cause any issue with TEtranscripts, except maybe slowing the run a bit. Have you tried re-running the program?

Thanks.

**Comment by dtx282000** [comment]
Hi, 

This job has ended. My command line as follows:

￼ 

￼


In, addition, I have tried re-running the command line again. Also I faced the same error.


Thanks！

**Comment by olivertam** [comment]
Hi,

Could you re-post your command lines again?
I cannot see them on Github.

Thanks.

**Comment by dtx282000** [comment]
HI, my command lines as follows:


### Run TEtranscripts
# Run samples in pairs
BAM_DIR="data/BAMs"
gene_annot_gtf="data/NDDB_SH_1_genomic_chr.gtf"
te_annot_gtf="data/Transposon_core_chr.gtf"
TETRANS_OUT_DIR="data/TEtranscripts”

cat ./data/aa.txt | while read i;

do

singularity exec /pub/software/tetranscripts.sif TEcount \
                --format BAM  --mode multi \
                -b  $BAM_DIR/${i}.bam \
                --GTF $gene_annot_gtf \
                --TE  $te_annot_gtf \
                --project  ${i} \
                --outdir  $TETRANS_OUT_DIR/reproductive
done

**Comment by olivertam** [comment]
Hi,

Thank you for your command line.
How much memory are you allocating (or have available) to run TEtranscripts?

Thanks.

**Comment by dtx282000** [comment]
￼

**Comment by olivertam** [comment]
Hi,

Sorry, again your response could not be seen on Github.

Thanks.

**Comment by dtx282000** [comment]
![image](https://github.com/user-attachments/assets/86f839b7-b3e1-499f-914f-c1992e4f548d)

**Comment by olivertam** [comment]
Thank you for your screenshot.
It looks like you have sufficient memory to run this, so I can't determine what the error is.
Is the final line of the log file (when it crashes) `Hangup` as indicated in your initial post?
Given that you're running a loop of `TEcount`, did every one of those runs fail (i.e. no output files generated)?
Thanks

**Comment by dtx282000** [comment]
Hi，

Strangely, the other samples were analyzed normally, but only one of them was the case (error: Hangup)

Thanks

**Comment by olivertam** [comment]
Hi,

Do you notice anything unusual about the BAM file for the one that failed (e.g. size, `samtools quickcheck`)
Might I suggest re-running the alignment for that particular sample?
It sounds like it might be an issue with that particular input, as the other samples ran fine (which suggests it's not an issue with the GTF or the program itself).

Thanks.

**Comment by dtx282000** [comment]
Hi,

According to your suggestion, I run the alignment for the particular sample again. Also, I performed the sort for this sample bam file. The following code was used:

<img width="683" alt="image" src="https://github.com/user-attachments/assets/1429ba60-b206-4676-b45f-b8288bcb16a6">

Looking forwards to your reply.

Thanks!

**Comment by olivertam** [comment]
Hi,

That is really strange. I have never encountered that error before (nor have I seen `Hangup` in the error message before).
Could you confirm that in your other runs, you also got the following in your log file?
```
[E::idx_find_and_load] Could not retrieve index file for ....
```
Do you have a time-limit on your jobs?
What system are you running this on (i.e. what OS or cluster manager)?

Sorry if this has been not helpful.

Thanks
