### ISSUE TITLE
Error: TE_anno.gtf

### ISSUE THREAD

**Issue by dtx282000** [mhammell-laboratory/TEtranscripts#199]
Hi, when I run the script, I encounter one error as follows:

<img width="990" alt="image" src="https://github.com/user-attachments/assets/66f230f7-257c-402b-b69d-722ff7a62a6b">

So, how I can deal with it?

My TE gtf file as follows:

<img width="989" alt="image" src="https://github.com/user-attachments/assets/0b8d1ee1-600e-43da-a239-a686c8a04cf3">

**Comment by olivertam** [comment]
Hi,

Could you check that there isn't two tabs between the `.` and the `gene_id` on each row? The gap looks bigger than expected.
While the `/` in both the `family_id` and `class_id` won't break the tool, I would say that the `family_id` is the second value (e.g. `RTE-BovB` for the first line), and `class_id` is the first value (e.g. `LINE`).
Please let me know if this doesn't resolve your issue.

Thanks.

**Comment by dtx282000** [comment]
Hi,


As you expected, one more a gap. Now, it is ok


Thanks!
