### ISSUE TITLE
Does TEtranscripts support Windows?

### ISSUE THREAD

**Issue by Ranxuqing** [mhammell-laboratory/TEtranscripts#202]
Hi Oliver，
      I would like to confirm whether TEtranscripts supports Windows operating systems. I've noticed that the platforms mentioned in the `setup.py` file are Linux and MacOS, yet I received an affirmative response from ChatGPT. Additionally, I encountered issues while installing pysam.

      I am eagerly awaiting your clarification on this matter. Thank you in advance for your assistance.
![image](https://github.com/user-attachments/assets/c8cb39e2-1ee3-45ea-8f90-03ec560fd9f6)

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
`TEtranscripts` was designed for a Unix-based OS (e.g. Mac OS and Linux). It was not designed natively for Windows.
We would recommend trying something like [cygwin](https://www.cygwin.com/) to make a Linux virtual environment to install/use `TEtranscripts`
If you use `pip install TEtranscripts`, it should hopefully install the prerequisites allon with our software.

Thanks.

**Comment by Ranxuqing** [comment]
Thanks for your response and suggestions.
