### ISSUE TITLE
Which sequence search engine do you recommend for best comparison with your curated GTF files?

### ISSUE THREAD

**Issue by jacel** [mhammell-laboratory/TEtranscripts#203]
Hi, I am trying to look at repeat elements in different strains of mice. I am planning to run repeatmasker on the new long-read SPRET genome, and compare these results with your mm10 GTF. So I want to use the same sequence search engine you used, to ensure they are comparable. Do you recommend Cross_Match, RMBlast, HMMER, or ABBlast? And are there any other RepeatMasker options you recommend using? Thank you!

**Comment by olivertam** [comment]
Hi,

Thank you for your question.
We used the [UCSC RepeatMasker track](https://www.genome.ucsc.edu/cgi-bin/hgTables?db=mm10&hgta_group=varRep&hgta_track=rmsk&hgta_table=rmsk&hgta_doSchema=describe+table+schema), so following their approach would be best.

Thanks.

**Comment by jacel** [comment]
Ah UCSC has already run RepeatMasker on Spret so I will use this file. Thank you!
