### ISSUE TITLE
locating TEs, esp. in Retained Introns (RI)

### ISSUE THREAD

**Issue by tud03125** [mhammell-laboratory/TEtranscripts#204]
Hi Everyone,

I was successfully able to run TEtranscript using these codes in command line:
```
singularity exec tetranscripts.sif TEtranscripts \
    -t /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I3_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I4_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I5_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I6_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I7_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I8_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I9_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I10_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I11_sorted.bam \
    -c /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I1_sorted.bam \
       /home/tud03125/pipeline/mouse_liver_rnasplice/star_salmon/I2_sorted.bam \
    --GTF /home/tud03125/pipeline/Mus_musculus.GRCm39.112.gtf \
    --TE /home/tud03125/pipeline/mm39_rmsk_TE.gtf \
    --sortByPos
```
However, the boss I am working with is more interested in knowing where these TEs are located so that they can design primers for experimental validation. From TEtranscript, TEcount, or any of your programs, is there a way to map where these TEs are located, esp. in Retained Introns (RI) (most interesting since we are seeking dsRNA strands)?

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
We would recommend trying [TElocal](https://github.com/mhammell-laboratory/TElocal), which tries to quantify TE at a paricular locus. You will have to run each library separately, then join the output into a single table. You can then run DESeq2 (or any other differential analysis algorithm) to look for differentially expressed loci. You will need to download an indexed database for the TE annotations (available [here](https://www.dropbox.com/scl/fo/jdpgn6fl8ngd3th3zebap/AGsyeyn4HYp9OFwdlmvc4U0/TElocal/prebuilt_indices?rlkey=41oz6ppggy82uha5i3yo1rnlx&subfolder_nav_tracking=1&dl=0)), with the corresponding genomic location available [here](https://www.dropbox.com/scl/fo/jdpgn6fl8ngd3th3zebap/ACJd90BZ2kcgQQl_Yo70xcM/TElocal/annotation_tables?rlkey=41oz6ppggy82uha5i3yo1rnlx&e=1&subfolder_nav_tracking=1&dl=0)

One thing that I would confirm is that you are using the correct annotations, as it appears that your gene GTF (Mus_musculus.GRCm39.112.gtf) might be from Ensembl, while the TE GTF is designed for UCSC. Depending on your alignment, you might have issues with annotations if the chromosome names do not match.

Thanks

**Comment by olivertam** [comment]
Hi,

It is available [here](https://www.dropbox.com/scl/fo/jdpgn6fl8ngd3th3zebap/AOGhllfiM2pL2BLiSOjl7C8/TEtranscripts/TE_GTF/GRCm39_Ensembl_rmsk_TE.gtf.gz?rlkey=41oz6ppggy82uha5i3yo1rnlx&dl=0).

Thanks.

**Comment by tud03125** [comment]
@olivertam Thanks! Very helpful!

One, other question: for this one:
> You will need to download an indexed database for the TE annotations (available [here](https://www.dropbox.com/scl/fo/jdpgn6fl8ngd3th3zebap/AGsyeyn4HYp9OFwdlmvc4U0/TElocal/prebuilt_indices?rlkey=41oz6ppggy82uha5i3yo1rnlx&subfolder_nav_tracking=1&dl=0)), with the corresponding genomic location available [here](https://www.dropbox.com/scl/fo/jdpgn6fl8ngd3th3zebap/ACJd90BZ2kcgQQl_Yo70xcM/TElocal/annotation_tables?rlkey=41oz6ppggy82uha5i3yo1rnlx&e=1&subfolder_nav_tracking=1&dl=0)
For the annotation's table: https://www.dropbox.com/scl/fo/jdpgn6fl8ngd3th3zebap/ACJd90BZ2kcgQQl_Yo70xcM/TElocal/annotation_tables?rlkey=41oz6ppggy82uha5i3yo1rnlx&e=2&subfolder_nav_tracking=1&dl=0, for GRCm39, there's only GENCODE. The only Ensembl I found is in GRCm38. Do you know when I'll get one from Ensembl for GRCm39?

**Comment by olivertam** [comment]
Hi,

The GRCm39 Ensembl genomic locations are available [here](https://www.dropbox.com/scl/fo/jdpgn6fl8ngd3th3zebap/AHdJyKslt4bsiPGPkl6KFpU/TElocal/annotation_tables/GRCm39_Ensembl_rmsk_TE.gtf.locInd.locations.gz?rlkey=41oz6ppggy82uha5i3yo1rnlx&dl=0).

The genomic location is generated from the GTF used in `TEtranscripts`, so when you get the output from `TElocal`, the `transcript_id` should match up with the start of the row names. Unfrotunately, since `TEtranscripts` aggregates the information when quantifying, so you won't be able to assess expression per locus.

Thanks

**Comment by tud03125** [comment]
@olivertam So, I'm starting to run `TElocal`. For the TE annotation for that software, it only accepts those with `.locInd` at the end (from `TE annotation file needs to be a TElocal index, which will end in .locInd(base)` message). From your links, the closet I could get, with Ensemble and GRCm39 genome, the one I've used is `GRCm39_Ensembl_rmsk_TE.gtf.locInd`. That said, I'm having a hard time viewing contents of this file (`head`, `tail` or `cat` just shows gibberish, unreadable characters). Is there a way to view `GRCm39_Ensembl_rmsk_TE.gtf.locInd` file, or no need since it's the same as `GRCm39_Ensembl_rmsk_TE.gtf`?

**Comment by olivertam** [comment]
Hi,

The `locInd` file is in binary, so you can't read it as a text file. It is basically generated from the TE GTF, but stored as a pickle index that allows easy loading (since generating this index takes quite a long time, so not great if it needs to be created everytime).

Thanks.

**Comment by tud03125** [comment]
@olivertam One, other question: the `GRCm39_Ensembl_rmsk_TE.gtf.locInd.locations` file you gave me, which includes these information: `TE	chromosome:start-stop:strand`, is very helpful for mapping purposes, esp. since `TEtranscript` and `TElocal` just quantitates how many Genes and TEs are there. But, how do you use `GRCm39_Ensembl_rmsk_TE.gtf.locInd.locations` file for this mapping case, especially since `TElocal` states `TE annotation file needs to be a TElocal index, which will end in .locInd(base)`, thus I can only use `GRCm39_Ensembl_rmsk_TE.gtf.locInd` and not `GRCm39_Ensembl_rmsk_TE.gtf.locInd.locations` in `TElocal`, and I am not sure how to use it for `TEtranscript` either?
