### ISSUE TITLE
TE GTF format error

### ISSUE THREAD

**Issue by Kkk-2001** [mhammell-laboratory/TEtranscripts#205]
when i tried to build a TE index,there always show me that

INFO  @ Thu, 24 Oct 2024 11:14:53: Building TE index ....... 

chrA01	EDTA	DNA/Helitron	1241	1375	.	-	.	gene_id "nbis-gene-1"; transcript_id "TE_00008421"; ID "TE_00008421"; Method "homology"; Parent "nbis-gene-1"; 
TE GTF format error! There is no annotation at line 1. 
Error in building TE index
![fig](https://github.com/user-attachments/assets/5a570efd-3aa2-4185-98b0-540e350a5bf6)
and here is my part of TE.gtf
[TE_all2 - part1.gtf.txt](https://github.com/user-attachments/files/17500672/TE_all2.-.part1.gtf.txt)

hoping for your answer thanks

**Comment by Kkk-2001** [comment]
i have solved this problem by using the makeTEgtf.pl
however there is a new problem below
when finished buliding index,it shown this message:
Reading sample files ... 
 
[E::idx_find_and_load] Could not retrieve index file for '/home/wjb-z2/Kongfanzhe/RNA-seq-data/bam-maping/6h1/6h1.bam'
******NOT COMPLETE******* 
If the BAM file is sorted by coordinates,                                 please specify --sortByPos and re-run! 
Error: 0 
[Exception type: SystemExit, raised in TEtranscripts:320] 
![1](https://github.com/user-attachments/assets/504719eb-57c3-4f93-aa80-6c0a91dc6085)
hoping for your answer

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
What aligner are you using? If you're using HiSat2, you might need to specify `--no-mixed` and `--no-discordant` to remove discordant alignments (see [here](https://github.com/mhammell-laboratory/TEtranscripts/issues/184#issuecomment-2032187478)).
If this does not resolve your issue, please provide your `TEtranscripts` command line, the full header from your BAM file (`samtools view -H`) and the first 10 lines of your gene and TE GTF files.

Thanks.

**Comment by Kkk-2001** [comment]
i uesd  bowtie2 to align at first time
when i turned to use STAR to align with default parameter,it also shown that [E::idx_find_and_load] Could not retrieve index file for '/home/wjb-z2/K/RNA-seq-data/bam-maping/6h1/6h1Aligned.out.bam'
but it still keep running and solve the problem itself,and i finished the following steps

however a error appear in the following procedure
![1](https://github.com/user-attachments/assets/f317547f-24ee-4eb4-94b3-13f7dd9a6ce5)

**Comment by Kkk-2001** [comment]
hi,
i have checked my TE gtf file with head -
![2](https://github.com/user-attachments/assets/8d1397d4-d2b3-4e15-bdbe-1c81ab0c2181)
i think there might be something wrong with it, but this file is present by  the script makeTEgtf.pl
i'm wondering whether to input the TE gtf file like genome GTF file shown below
![3](https://github.com/user-attachments/assets/717bb2de-49eb-4677-bca3-7ab6aaba4085)
hoping for your answer thank you

**Comment by olivertam** [comment]
Hi,

You're right that the TE GTF is weirdly formatted, with a weird line break after the `family_id` value. I suspect that that might be in the input file (perhaps a non-Unix line break).
Could you provide the first 10 lines of the input that you used for the `makeTEgtf.pl` script?

Thanks

**Comment by Kkk-2001** [comment]
hi,
I changed the in put file,and it works;
however it shown me that TE inconsistency
how can i solve this problem
watching for your answer,thanks
TE inconsistency! 3000769..3005760#LTR/Copia:chrA01:3000769..3005760#LTR/Copia:LTR/Copia:LTR/Copia 
Error: 1 
[Exception type: SystemExit, raised in TEindex.py:380]

**Comment by Kkk-2001** [comment]
[TE0.zip](https://github.com/user-attachments/files/17539157/TE0.zip)
here is my gtf file,thanks for your patient and hoping for your answer

**Comment by Kkk-2001** [comment]
Thank you very much for your suggestion, the problem was resolved after removing the duplicates
But the final result file is only treatment_vs_control.cntTable, treatment_vs_control_DESeq.R,
treatment_vs_control_gene_TE_analysis.txt treatment_vs_control_sigdiff_gene_TE.txt is missing.
The error information is as follows
![新建会话 - wjb-z2@node2_~ - Xshell 7 (Free for Home_School) 2024_10_29 14_07_37](https://github.com/user-attachments/assets/9d9fd415-b367-4a2d-97cd-7c8f8dc9d508)
hoping for your answer

**Comment by olivertam** [comment]
Hi,

If you scroll down to the TE annotations, you will find that there is a "hidden" line-break in the output. This is typically introduced by Mac or Windows, as they use a different line break character than Unix.
A quick fix for your `cntTable` file is:
```
$ sed -i 's/\r//g' 6_vs_0.cntTable
```
You will probably need to do the same to your GTF file, since that's where the error was propagated from.

Thanks.

**Comment by Kkk-2001** [comment]
hello thanks for your help and patient,finally i completed the analysis
i am wondering that whether the number in the result flie is the FPKM of TE or other value（like TPM）
thanks for your help again

**Comment by olivertam** [comment]
Hi,

`TEtranscripts` aggregates counts from different copies of a TE subfamily to enable better statistical analysis. This is done by combining counts based on the `gene_id`.
The `cntTable` file contains the raw count. The `gene_TE_analysis.txt` contains the output from `DESeq2`, which is normalized mean (done by `DESeq2`) across all samples (`baseMean`), log 2 fold change (`log2FoldChange`), the standard error on fold change (`lfcse`), the raw p value (`pval`) and BH-corrected p value (`padj`). The `sigdiff_gene_TE.txt` contains the hits that were significant based on the significance threshold used (default is 0.05).

Thanks

**Comment by Kkk-2001** [comment]
hi！
Sorry to bother you again, 
i'm wondering that if I only need TE information but not genes, can I output only information about TE？
after checking the output file, i found that the results were concentrated on some chromosomes and not at all on others
I wonder if it's caused by the quantity of genes and TEs is over the limit and make the result incomplete

**Comment by olivertam** [comment]
Hi,

If you just want the TE output, you can just `grep` for lines with a `:`.
I'm not sure what you mean by the results being concentrated on some chromosomes. Please be aware that the TE results are aggregated by `gene_id`, which should contain entries from multiple chromosomes, so it's not clear how you would have determine which chromosomes were "concentrated".

Thanks.
