### ISSUE TITLE
Could not retrieve index file When I run the TEtranscripts though I deal with Gene and TE gtf

### ISSUE THREAD

**Issue by 1228849000** [mhammell-laboratory/TEtranscripts#207]
Hello,
I'm sorry to distrub you. I encountered an error while running TEtranscripts that states it
cannot retrieve the index, but my BAM files do have an index(.bai).I don’t know why.
Please forgive me for the disturbance.
![1](https://github.com/user-attachments/assets/3adc47d5-b187-4178-95fa-79a60fa221c3)

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
This is a warning message from `pysam`, but it appears to have no impact on the running of the software (see also #185). 
If the appropriate output files are generated (e.g. `xxxx.cntTable`), then you can safely ignore the message.

Thanks.
