### ISSUE TITLE
TE GTF for non-model species

### ISSUE THREAD

**Issue by canyon-hub** [mhammell-laboratory/TEtranscripts#209]
Hello,

I’m very excited to use TEtranscripts. However, I work with a non-model genome, and there are no gene and TE annotation files available on your website for this species. Would it be possible for me to create the necessary files on my own? I currently have TE annotations generated by RepeatMasker.

I look forward to your response!

Thank you very much.
canyon

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
You can use the following [script](https://www.dropbox.com/scl/fi/jdddmextt4w774h9ndli9/makeTEgtf.pl.gz?rlkey=ezanzt5sttb9rw07e7s0janwp&st=n13ude52&dl=0) to process the RepeatMasker output to a TE GTF annotation.
Let us know if you encounter any issues, and we can try to help and troubleshoot.

Thanks.

**Comment by olivertam** [comment]
HI,

The alignment score is not essential for the TE GTF.

Thanks.
