### ISSUE TITLE
TE sequence Issue

### ISSUE THREAD

**Issue by Jinloong-dream** [mhammell-laboratory/TEtranscripts#210]
Hi,
Professor!
I used to 'TEtranscripts' of your lab to analyse non-model mammal genome, TE GTF generated by RepeatMasker and perl script from your lab. As I want to get certain TE's sequence (eg. LINE1) for further research, how can i get this. I have tried TBtools, it worked for genes, but not for TEs. 

Best wishes!

Jinloong,
ZhaoLab of ZJU

**Comment by olivertam** [comment]
Hi,

If you're interested in the consensus sequences for the transposable elements, you can obtain them from [Repbase](https://www.girinst.org/) or [Dfam](https://dfam.org/). If you want a specific TE copy in your non-model mammal genome, you can use [BEDtools](https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html) by providing the genome sequence and the genomic coordinates of interest.

Please let us know if this does not address your question.

Thanks.

**Comment by Jinloong-dream** [comment]
Hi
Professor！
Thanks for replying so fast. Sorry I just solved the problem till now, thanks to your advice. I used bedtools to generate a fasta file, adding the TE id and motifs to the head of fasta file, so that the TE id from TEtranscripts_sigdiff file can be directly used for searching in the fasta file.

Best Wishes.

Jinloong


> Hi,
> 
> If you're interested in the consensus sequences for the transposable elements, you can obtain them from [Repbase](https://www.girinst.org/) or [Dfam](https://dfam.org/). If you want a specific TE copy in your non-model mammal genome, you can use [BEDtools](https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html) by providing the genome sequence and the genomic coordinates of interest.
> 
> Please let us know if this does not address your question.
> 
> Thanks.
