### ISSUE TITLE
Counting read problems + extract sequences & genomic positions for specific TEs

### ISSUE THREAD

**Issue by lfra** [mhammell-laboratory/TEtranscripts#49]
Hi,

I have two (somewhat unrelated) questions concerning your toolkit/TE annotation. 

1) Counting reads that map to overlapping non-TE genes

I have been successfully using your tool quite a lot recently and also done DGE analysis (DESeq2) on the resulting count tables. For non-TE genes I have noticed that my annotation (hg38 with gencode v31) contains some annotated genes/features that are partially or even completely overlapping. Tomy knowledge this only affects the histone cluster genes (HIST...XX) which are a nightmare of overlapping genes.
Consequently, when TEtranscripts counts reads that map to some of those overlapping features it assigns the counts to EITHER of the overlapping features, while the others get 0. I noticed this, because I even had this discrepancy between replicates of the same sample (e.g. 0 counts in rep1 and >20000 counts in rep2. and it seemed randomly changing between samples. The mapping (IGV tracks of BAMs) was normal - so it was really a result from counting.
This is a huge problem, because depending on how they get counted between conditions they may pop up as (very!) significantly differentially expressed during the DESeq2 analysis afterwards.

Is there any way to tell TEtranscipts not to count reads that map to overlapping features?
I solved it now by removing genes with too many (arbitrary threshold e.g > number of conditions/number of replicates )zero counts afterwards for all samples, but there has to be a better way, since anyway you don't want to make assumptions on reads that you cannot uniquely assign to one annotated feature.

2) What would be the easiest way to extract the sequences from a specific annotated repeat/TE or even a repeat family in the hg38_TErmsk.gtf (of course from the fasta hg38 genome sequence to which I mapped to). I have some differentially expressed repeats in my experiment and would like to look 
1. whether there is a bias/preference for location along chromosomes (for which I would need the coordinates)
2. how many of those sequences are in the annotation 
3. how the sequences are structured (for which I would need to extract all the fasta sequences for one annotated repeat to do alignments, design primers etc.)

I know that this is a bit beyond your tool, but some ideas would be really appreciated ;-)
Especially since you mentioned in the vignette/paper that the format of your TE annotation file hg38_TErmsk.gtf is not just simply the repeat masker track gtf.

Thank you very much in advance!

Best,

Lukas

**Comment by olivertam** [comment]
Hi Lukas,

I will need to further investigate the histone gene issue before I have a good response for that.

For your second question, the first thing that you would need to do is to generate a GTF containing the subset of TE/repeat family that you would want. For example, if you want all instances of L1HS, you can try
```bash
$ grep -w "L1HS" hg38_rmsk_TE.gtf > hg38_L1HS.gtf
```
If you have several features (e.g. L1HS, L1PA6, L1PA2), you can put them all into a text file (separate each entry by a new line), and try this:
```bash
$ grep -w -f selectedTE.txt hg38_rmsk_TE.gtf > hg38_selectedTE.gtf
```
Once you have the selected TE in the GTF format, there are two ways that you can extract sequences:  gffread (see [here](https://www.biostars.org/p/123166/) for an example), or convert the GTF coordinates to BED, and use bedtools [getfasta](https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html).

Please let me know if there are any questions about getting the specific TE, and I will get back to you regarding the histone overlapping features as soon as possible.
Thanks.

**Comment by olivertam** [comment]
Hi Lukas,

Regarding the overlapping features, have you attempted to run one of the replicate (let's say rep 1) with two separate runs of TEcount? Are you seeing differences from run to run of TEcount, or just from sample to sample?
This might help us determine if it is randomly assigning reads for each run, or if there's something inherent in the samples (between rep1 and rep2) that might be causing the differences.
Thanks.

**Comment by lfra** [comment]
Hi Oliver,

thank you for the fast reply and the answers! Regarding the histone cluster question I will have a test run on the same replicate and come back with the results asap.

Thanks,

Lukas

**Comment by lfra** [comment]
Hi,
I ran TEcount on the same replicate/sample 4 times and the output is absolutely identical (same md5sum of count files).

But what is really weird is that I when I had the problems with the histone genes in my analysis, I also compared the IGV tracks of the BAM files to the counts for specific histone cluster regions, and the track looked absolutely identical in terms of coverage, but the counts in one replicate were 0 and in the other one e.g. >20000. So it clearly has to be somewhat of a counting issue.

If I understood correctly, you use pysam for counting in TECount?
Does it perform any filtering of the reads that are counted (for some flags or MAPQ?)

Hope this helps. Thanks a lot.

Lukas

**Comment by olivertam** [comment]
Hi Lukas,

Thank you for your help. I saw the same results as you (identical output from the same replicate). This suggests that the "random" allocation of reads is not truly random (i.e. not decided at run-time), but is somehow biased by the BAM sample. I agree with you that it is a counting issue, but it's not immediately clear what could be causing it.
You are correct that we are using pysam for the counting, but we do not filter the reads except to look for correctly paired reads when working with PE samples.
I'm sorry to keep bothering you, but I'm curious to know if you still see the same results when using the "uniq" mode `--mode uniq`. This should only take unique mappers, and thus determine if the discrepancy is somehow inherent in the unique mappers (maybe certain libraries mapped differently, especially if they are paired-end).
I'll keep investigating on my end.
Thanks again for all your help.

**Comment by olivertam** [comment]
Hi Lukas,

If you don't mind, would you be able to provide the command line that you're using for TEcount?
Thanks

**Comment by lfra** [comment]
Hi,
sure.

TEcount --sortByPos --stranded reverse --format BAM --mode multi -b /path/to/BAM/sample_Aligned.sortedByCoord.out.bam --GTF /path/to/gtf/hg38_gencode.v31.annotation.gtf --TE /path/to/TEgtf/hg38_rmsk_TE.gtf --project sample_TE_counts_reverse

The BAMs are an output of STAR version 2.5.3a with re-defined parameters
--outFilterMultimapNmax 100 --winAnchorMultimapNmax 100
and the very same gene GTF file(hg38_gencode.v31.annotation.gtf) provided during the mapping.

Thanks,

Lukas

**Comment by olivertam** [comment]
Hi Lukas,

Thank you for the command line. Are you sequencing single-end or paired-end?

**Comment by lfra** [comment]
Hi,

this particular dataset (on which I ran the 4 test runs) is paired-end. But I had the same histone gene problem with another single-end dataset.

**Comment by olivertam** [comment]
Hi Lukas,

Thanks for your response. We are still looking into it, and have not found an obvious reason for your observations. We'll let you know if we find anything.
Thanks again. All the best.
