### ISSUE TITLE
Double Checking Strandedness Flag Meaning

### ISSUE THREAD

**Issue by jimcdonald** [mhammell-laboratory/TEtranscripts#50]
Hammell Lab,

We recently realized we were using the wrong strandedness flag when analyzing some of our RNA-seq libraries. The documentation here doesn't specify the specific meanings of the strandedness options, which are the same as those in HT-Seq. However, I do not know for sure if they mean the same as they do in HT-Seq. As we double check our work, I wanted to double check the meanings of the flags so that we can be sure to run TEtranscripts correctly the next time:

1. Stranded = yes. Use this for stranded libraries that are "second strand" libraries such as those produced by the Scriptseq kit with a 3' tagging procedure. See page 4 of the Scriptseq manual for an example: https://www.westburg.eu/uploads/fckconnector/c28b946b-4bc7-4c09-abd3-f50a0ff572ce

2. Stranded = reverse. Use this for stranded libraries that are "first strand" libraries such as protocols using dUTP like the Illumina Truseq protocol.

Is this correct?

Thank you!
James

**Comment by olivertam** [comment]
Hi James,

I'm sorry to hear that you had issues with the software.
Yes, you are correct on both 1 and 2.
`--stranded yes` means that it is a "second strand" library, where read 1 is in the direction of transcription (second strand cDNA). Scriptseq is a good example
`--stranded reverse` means that it is a "first strand" library, where read 1 is in the reverse direction of transcription (first strand cDNA). Illumina Truseq is a good example.
Apologies for the confusion. We will clarify the documentation to prevent future issues.
Thanks.

**Comment by jimcdonald** [comment]
It's not your fault. We mixed up which libraries were made with which RNA-seq kit. I just wanted to make sure I did the right thing for sure the second time.

Thanks for confirming I have things right this time around!

James
