### ISSUE TITLE
Input with STAR aligned and chimeric BAM files?

### ISSUE THREAD

**Issue by evanwangx** [mhammell-laboratory/TEtranscripts#51]
Hello,

I have been provided with BAM files that have already been mapped using STAR and I'd like to try your tool. The issue is that there is both an Aligned and a Chimeric output for each sample. Should I be counting both files and merging the count tables for each sample?

Thank you

**Comment by olivertam** [comment]
Hi,

It would really depend on what you are hoping to quantify. If you are interested in "canonical" transcripts (e.g. GENCODE), then you would probably get more useful results if you're using the Aligned BAM files.
If you are interested at the chimeric transcripts detected, then other tools (or a customized annotation GTF file that you curated) might be more appropriate.
Please let me know if anything is unclear.

Thanks.

**Comment by evanwangx** [comment]
Hi Oliver,
Thanks for your response. What kind of custom annotation GTF do you recommend to quantify TEs that are incorporated into chimeric transcripts?

**Comment by olivertam** [comment]
Hi,

If you are trying to quantify de-novo chimeric transcripts, or see what chimeric transcripts have incorporated TE, then I would suggest another tool. 
If you already have a list of known/previously identified chimeric transcripts with TEs, and you want to quantify those particular transcripts, then you could potentially use TEtranscripts (but with caveats). 
Let me know if this is unclear.

Thanks.
