### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by dpryan79** [mhammell-laboratory/TEtranscripts#61]
Since python 2 is officially dead, would it be possible to update this to work with python 3?

**Comment by olivertam** [comment]
Hi,

We are still working out how best to proceed, as most of our users are still dependent on python 2, so we want to make sure that our code could be python 2 and python 3 compatible.
If that proves too problematic, then we might have to release a separate branch to run under python 3 (which we are currently testing).

Thanks.

**Comment by olivertam** [comment]
Hi @dpryan79,

We have added Python 3 compatibility to TEtranscripts (as of version 2.2.0).
Please let us know if you encounter any issues.

Thanks.

**Comment by millerh1** [comment]
Hi @olivertam could you update the conda release to the version with python3 compatibility? It's currently stuck at 2.0.3. Thanks!

**Comment by olivertam** [comment]
Hi,

I am seeing the version on [bioconda](https://bioconda.github.io/recipes/tetranscripts/README.html) as 2.2.1.
Could you let me know what you see when you run `conda search -f tetranscripts`?
Please note that tool name was changed from TEToolkit to TEtranscripts as of version 2.0.4, which might be why it looks like it's stuck at version 2.0.3.

Thanks.

**Comment by millerh1** [comment]
OH! I was looking at the conda page for tetoolkit https://anaconda.org/bioconda/tetoolkit

My Bad!

**Comment by olivertam** [comment]
No worries.
Good luck with the install.
