### ISSUE TITLE
how to deal with duplicates in data from RNA-seq or scRNA-seq?

### ISSUE THREAD

**Issue by AIBio** [mhammell-laboratory/TEtranscripts#64]
Hi~
I have read the paper your group has published. (Analysis of RNA-Seq Data Using TEtranscripts)
I found the duplicates in RNA-seq data are not removed. For mRNA-seq data, I agree with it. But  when confronted with scRNA-seq data (from smart-seq2), I'm not sure whether the duplicates are removed or not. Especially, I have to quantify TE from scRNAseq data through TEtranscripts! To my knowledge, somebody do remove duplicates in scRNAseq analysis pipeline. Surely, somebody not do it. But most of them focus on protein-coding genes. Do you have any advices about quantifing TE from scRNA-seq data?
Best wishes from Hanwen Yu
31th March, 2020

**Comment by olivertam** [comment]
Hi,
You are correct that duplicates are not removed in our analysis pipeline, as that would remove a lot of repetitive sequences. Without a UMI system, it would be very difficult to remove duplicates without eliminating reads from a repetitive region.
One thing that you can try is to try using TEtranscripts on your scRNA data with or without duplicate removal, and see how much of a difference it makes on gene vs TE-derived transcripts.
We are still developing a protocol that could handle these type of data (which may or may not involve a new tool). Keep watching [this space](https://github.com/mhammell-laboratory/) :)
Thanks

**Comment by AIBio** [comment]
Hi,
Thank you for your reply. Looking forward to more excellent works from your group!
Hanwen Yu
