### ISSUE TITLE
Intronic TEs

### ISSUE THREAD

**Issue by jentiger82** [mhammell-laboratory/TEtranscripts#65]
I have a question regarding the analysis of genes and TEs with TEtranscripts. I usually only use the TE counts for further analysis. I have a question of how you differentiate between genic regions and TEs: Do you only count reads mapping to exons of genes or also intronic reads? I am asking because of TEs within intronic regions and wondering if the counts are allocated to the gene or TE or both?

Thanks, Jenny

**Comment by olivertam** [comment]
Hi Jenny,

We are only considering exonic regions as "genic", as the program is designed with RNA-seq as the primary usage. Intronic reads that overlap TE will be allocated to the transposable element.

Thanks.

**Comment by laijen000** [comment]
Hi @olivertam, I have a related question -- is there an option for TEtranscripts to estimate the abundance of a TE on an instance or region level? For example, can we get counts data for TEs in intergenic regions v. introns? Thank you!

**Comment by olivertam** [comment]
Hi,

If you're interested in quantification of TE at an instance/locus level, you can try [TElocal](https://github.com/mhammell-laboratory/TElocal), which is currently in beta.
It would require a different GTF to the one used by TEtranscripts, and we would recommend using a pre-built index (available [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/)), as it takes a long time to build one from a GTF. 
If the genome version is not available, let us know and we can try to build one for you (though it would take some time).

Thanks
