### ISSUE TITLE
Error for differential expression analysis

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [mhammell-laboratory/TEtranscripts#67]
Hi there,
Thanks for making TEtranscript. I am running 2.14.

I get the following error and I am unsure what file is actually wrong.

INFO  @ Tue, 21 Apr 2020 01:35:37: Finished processing sample files
INFO  @ Tue, 21 Apr 2020 01:35:37: Generating counts table
INFO  @ Tue, 21 Apr 2020 01:35:38: Performing differential analysis ...

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 37218 did not have 7 elements
Calls: read.table -> scan
Execution halted

The cntTable file looks good as inspected via command line and in pandas.

**Comment by olivertam** [comment]
Hi,

Would you be able to provide the `XXXX.cntTable` file? Based on the error message, I'm suspecting that there might be an odd character on line 37218 (extra tab or a `#` symbol?) that might be throwing off the `read.table` R command.

Thanks.

**Comment by BenjaminSchwessinger** [comment]
Thanks for the quick reply. I changed the ending to txt.
[haustoria_infectedWheat7.txt](https://github.com/mhammell-laboratory/TEtranscripts/files/4506454/haustoria_infectedWheat7.txt)

**Comment by olivertam** [comment]
Hi,

It looks like the error is actually on line 37219 of your file (line 37218 excluding the header line):
```
BNINTMO_#2_ClassI_LTR_Gypsy:LTR_Gypsy:ClassI_LTR	37	53	29	29	43	63
```
In fact, I noticed many more lines where the `#` symbol exists. This is a reserved character in R (and most programming languages) to indicate that the rest of the line is a comment. Thus, everything after it is "lost", and why `R` says that there are insufficient columns of information.
The quickest way to fix this is to substitute all `#` with something else (or remove it completely).

Thanks.

**Comment by BenjaminSchwessinger** [comment]
Great. Thanks. Didn't know this default behaviour in R as pandas handled it just fine.

I will fix this in the TE gtf file with sed to * and report back here if it all worked.

Your help is much appreciated.
________________________________

**Comment by BenjaminSchwessinger** [comment]
All fixed. Closing the issue.
