### ISSUE TITLE
Create TEGroomer Functionality 

### ISSUE THREAD

**Issue by molikd** [mhammell-laboratory/TEtranscripts#7]
The idea being that we could convert from GFF to GTF and/or check for common "mistakes" in GTF files.

**Comment by olivertam** [comment]
Should we allow conversion from BED, UCSC rmsk database dump and other custom files? I like the idea of checking for common mistakes. Perhaps we can take part of the code from TEtoolkit that tries to build the index, and make it do a test build (as part of the grooming)?

**Comment by status-five** [comment]
Hmm, I'm trying to come up with a core functionality list... 

Things to check: 
- Repeated Entries
- Spacing
- Notation ( see: #6 ) 
- Do we fix the GTF file, or perhaps prompt the fix if we find these things? 

conversions as well:
- BED
- GFF3 (maybe/maybe not, cufflinks has this)
- UCSC rmsk

run testing: 
- it's probable we can use TEIndex 

we could do this with sub-commands, it would be something like:

- TEGroomer Convert <file> 
- TEGroomer Test <file>
- TEGroomer Groom <file>
