### ISSUE TITLE
TEtranscripts stopped at TE index building step

### ISSUE THREAD

**Issue by hugch2010** [mhammell-laboratory/TEtranscripts#71]
Hi,
I'm using TEtranscripts 2.1.4 to analyzing TE expression in mouse RNAseq data with mm10_rmsk_TEinst.gtf. The analysis process was held at the "Building TE index" step, the task has been  running for a whole day with no error reported. Please give me some suggestions.
Thank you
Gongcheng

**Comment by olivertam** [comment]
Hi,

Please use the [mm10_rmsk_TE.gtf](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/mm10_rmsk_TE.gtf.gz) file instead. 
The one that you have downloaded is for another program ([TElocal](https://github.com/mhammell-laboratory/TElocal)), and takes a long time to build.

Thanks.

**Comment by hugch2010** [comment]
Yes, I misused the wrong gtf, the new gtf works fine. Thanks.
