### ISSUE TITLE
No .txt output files

### ISSUE THREAD

**Issue by maureenwidyawan** [mhammell-laboratory/TEtranscripts#74]
Hi, 

I tried your example data for testing, however there were only 2 output files (singleEnd_test.cntTable and singleEnd_test_DESeq2.R). There were no singleEnd_test_gene_TE_analysis.txt and singleEnd_test_sigdiff_gene_TE.txt output files (it's the same for paired-end test).

Why there are no .txt output files?

**Comment by olivertam** [comment]
Hi,

Sorry for the slow response.

A possible reason could be that `DESeq2` was not installed.
If you could run the following command line:
```bash
which Rscript
```
It should indicate whether R is installed.
Then you can run: 
``` bash
Rscript singleEnd_test_DESeq2.R
```
in the folder with the testing output, and see what messages are printed. This would give us a hint whether it is due to the `DESeq2` package, or something else.

Thank you for your interest in the software.

**Comment by maureenwidyawan** [comment]
Hi,

Thank you for your reply. This problem was caused by DESeq2 not installed properly. It was solved by re-installing Rscript and DEseq2.

Thank you for your help.

**Comment by tongyin121** [comment]
Hi, I met the same output files as the former questioner. However, the DESeq2 package was installed properly and used the command Rscript TEtranscripts_out_DESeq2.R, then I got the TEtranscripts_out_sigdiff_gene_TE.txt and TEtranscripts_out_gene_TE_analysis.txt. Therefore, I am wandering if I should run the pipeline by these two parts every time , or have other ways to run the pipeline as one step.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
If DESeq2 is installed properly, it should generate the output text files through TEtranscripts, so it is unusual that it only works when you run it through command line.
Could you paste the log output from your run? There might be error messages that could explain the discrepancy.

Thanks.

**Comment by tongyin121** [comment]
Thank you for your reply, here is the log file.
[out.log](https://github.com/mhammell-laboratory/TEtranscripts/files/8189861/out.log)
.

**Comment by olivertam** [comment]
Hi,

It appears that TEtranscripts had trouble calling `Rscript`:
```
Error in running differential analysis! 
Error: [Errno 2] No such file or directory: 'Rscript' 
[Exception type: FileNotFoundError, raised in subprocess.py:1326] 
```
Are you running TEtranscripts in a separate environment/cluster? This error suggests that `Rscript` was not on the path of executables (typically indicated by the `PATH` variable).

Thanks.

**Comment by tongyin121** [comment]
Hi, sorry for my late reply, I have tried the approach you had said to me. The error of  "No such file or directory: 'Rscript' " have solved, but there is another error generated. Here is the new log file. I actually installed the package named 'DESeq2', it can be load in the environment which contain both R4.0 and python3.6.  
By the way, does the "TEtranscripts_out_DESeq2.R" have the same output files as the main program.
[multi.out.log](https://github.com/mhammell-laboratory/TEtranscripts/files/8241201/multi.out.log)

**Comment by olivertam** [comment]
Hi,

Yes, the output files from the R script would be the same as the main program (it is just running the R script after it's generated).
From your log file, it appears that DESeq2 was not detected on the version of R that was being called by Rscript. I'm assuming that you're using a conda-like environment, and R and conda have a history of not working great together. If you have multiple versions of R, you might need to confirm that you've installed DESeq2 in the version of R in your active conda environment (where you run TEtranscripts) and not the system/user version. You would then probably want to check that the version of Rscript called when running TEtranscripts is the same as the one when you call on its own.
Hope this is helpful. If it's too problematic, then running the outputted R script afterwards is perfectly fine.

Thanks.

**Comment by tongyin121** [comment]
Hi, I have solved this problem already by listening your advice. I am so appreciate for your reply!
