### ISSUE TITLE
Question about the hg19_rmsk.vcf file

### ISSUE THREAD

**Issue by xunchen85** [mhammell-laboratory/TEtranscripts#78]
Hi,

I have used the hg19_rmsk.vcf file for some analyses. I am trying to find the original repeatmasker alignment output file. I am wondering where I can find it?

I have tried the repeatmasker human reference database http://www.repeatmasker.org/species/hg.html. There are many versions of hg19, although none of them exactly matched the one I obtained from the TEtranscripts webpage.

Thanks for your help,
Xun

**Comment by olivertam** [comment]
Hi,

We are using the RepeatMasker output provided by [UCSC](http://genome.ucsc.edu/cgi-bin/hgTables), specifically the rmsk table (downloadable [here](http://hgdownload.cse.ucsc.edu/goldenpath/hg19/database/rmsk.txt.gz)).
We then process the rmsk table with a custom Perl script to generate the GTF file that we provided on our webpage.
Please let us know if you have further questions.

Thanks.

**Comment by xunchen85** [comment]
Hi,

Thanks very much for your quick response.

I will check if i can find any information from UCSC pointint me to the original repeat alignment results.

Best,
Xun
