### ISSUE TITLE
TEcount can be run on multiple BAM files?

### ISSUE THREAD

**Issue by my0916** [mhammell-laboratory/TEtranscripts#80]
Hello.

We would like to try TEcount rather than TEtranscripts for our ~50 samples in several groups, but is it possible to run TEcount  on multiple BAM files as `-t RNAseq1.bam RNAseq2.bam` in TEtranscripts? Only one BAM file can be assigned for `-b` option? 

And our BAM files contain PCR duplicates (SAM flag: 1024) based on UMI, then should we process the data after removing these duplicate reads?
I've already read this: https://github.com/mhammell-laboratory/TEtranscripts/issues/64

Thank you.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software. TEcount is designed to work on a single BAM file at a time, and it is designed to enable parallel processing of multiple libraries. Thus, if you have sufficient CPU and memory (e.g. access to computing cluster), you can run multiple TEcount at once. We would recommend at least 30G of memory (for human genome) per TEcount run.
If you are able to determine PCR duplicates with confidence (e.g. with UMI), you can try removing them from the BAM before running. I would definitely compare the results between removing and keeping the duplicates to see if there is a preferential loss of a particular class of transcripts.
Thanks.

**Comment by my0916** [comment]
Thank you very much!
