### ISSUE TITLE
Count output for paired end reads

### ISSUE THREAD

**Issue by emattei** [mhammell-laboratory/TEtranscripts#84]
Hi, If I run TEtranscripts with a bam containing paired-end reads the '.cntTable' will report reads or fragments?

Thank you

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
The count table will report fragment counts when working with paired-end data.

Thanks.

**Comment by emattei** [comment]
Perfect, thank you vey much for the clarification!
