### ISSUE TITLE
error while running TE counts

### ISSUE THREAD

**Issue by amitpande74** [mhammell-laboratory/TEtranscripts#86]
Hi,
Am getting an error while running TE counts:
```
TEcount --format BAM --mode multi -b sorted.bam --project sample_nosort_test --GTF refseq_hg19.gtf  --TE hg19_rmsk_TE.gtf --mode uniq --verbose 3 --sortByPos
INFO  @ Thu, 31 Dec 2020 12:58:13: 
# ARGUMENTS LIST:
# name = sample_nosort_test
# BAM file = sorted.bam
# GTF file = refseq_hg19.gtf 
# TE file = hg19_rmsk_TE.gtf 
# multi-mapper mode = uniq 
# stranded = no 
# number of iteration = 100
# Alignments grouped by read ID = False

 
INFO  @ Thu, 31 Dec 2020 12:58:13: Processing GTF files ... 
 
INFO  @ Thu, 31 Dec 2020 12:58:13: Building gene index ....... 
 
100000 GTF lines processed.
200000 GTF lines processed.
300000 GTF lines processed.
400000 GTF lines processed.
500000 GTF lines processed.
600000 GTF lines processed.
700000 GTF lines processed.
INFO  @ Thu, 31 Dec 2020 13:07:37: Done building gene index ...... 
 
INFO  @ Thu, 31 Dec 2020 13:07:45: Building TE index ....... 
 
INFO  @ Thu, 31 Dec 2020 13:11:09: Done building TE index ...... 
 
INFO  @ Thu, 31 Dec 2020 13:11:09: 
Reading sample file ... 
 
[E::idx_find_and_load] Could not retrieve index file for '.1609416669.057831.bam'

```
Error occurred during read assignments 
Error occurred when processing annotations of DBV2SVN1:183:C52GNACXX:2:1308:3676:72707 in file sorted_PE12.bam. 
Can your kindly help.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
This has been reported previously (see [here](#82)), and it is related to a quirk with a newer [samtools/pysam](pysam-developers/pysam#939).
We have found that this is a warning message that does not appear to affect the quantification step, and in our testing, the same results are generated whether the warning message was present or not.
We have considered suppressing the warning message, but worry that this might prevent the problem from indicating actual problems, and thus have so far decided to let it be.
Hope this helps.

Thanks.

**Comment by amitpande74** [comment]
Dear Oliver,
I thought it was a mistake from my side that while using STAR aligner, I resorted to Galaxy for aligning the FastQ files. Shall keep you updated. Thanks for your quick response.
