### ISSUE TITLE
GTF files for macaques, bonobo, and also external index

### ISSUE THREAD

**Issue by ferygood** [mhammell-laboratory/TEtranscripts#91]
Hello Oliver,

I would like to use TEtranscripts to analyze TE in primates. However, I do not find all gtf files I want in the archive. Could you provide TE gtf files for macaques (rheMac10) and bonobo (panPan3)? I also see there is pre-generated hg38 index for speed up the analysis in one of the closed issue. Do you think it is also possible to provide index for Chimpanzee (panTro6), macaques (rheMac10) and bonobo (panPan3)? 
That would be very nice for running huge sample numbers. Thank you for your time.

Best

**Comment by olivertam** [comment]
Hi,

The GTF files for rheMac10 and panPan3 should be [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/), and the pre-built indices for panTro6, rheMac10 and panPan3 should be [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/prebuilt_indices/).
Please let me know if you have trouble finding them, or if they don't work.

Thanks.

**Comment by ferygood** [comment]
Hello Oliver,

Thank you for your immediate reply, I am able to find these files now.
I will let you know if I encounter any problems.
Many thanks!

Best
