### ISSUE TITLE
counts for individual Transcripts of TE gene 

### ISSUE THREAD

**Issue by yingyin2019** [mhammell-laboratory/TEtranscripts#92]
Hi, 
   We notice that "TEcounts" output only contain counts for  combination of all transcripts in one particular TE gene (*.cntTable). Is there any way to get counts for individual transcript for this gene. 
   Thanks, 
  Best, 
  Ying

**Comment by olivertam** [comment]
Hi Ying,

We would recommend trying [TElocal](https://github.com/mhammell-laboratory/TElocal) with the corresponding [pre-built indices](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/).

Thanks.
