### ISSUE TITLE
GTF files for rice, also external index

### ISSUE THREAD

**Issue by zhangaicen** [mhammell-laboratory/TEtranscripts#96]
Hello Oliver,
  I'd like to use TEtranscripts to analyze TE in rice (Oryza sativa japonica), however I don't know how to get the TE GTF and index files in the given website, while most of the files in the web is about animals.  My reference genome is Nipponbare reference genome (MSU v7.0, [http://rice.plantbiology.msu.edu/pub/data/Eukaryotic_Projects/o_sativa/annotation_dbs/pseudomolecules/version_7.0/all.dir/]).

So could you tell me how can I get the TE GTF file?

Thanks very much for your time.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software. If there is a file within that contains the location and identity of transposable elements (or repeats in general) in the MSU v7.0 database, you can either use a perl script (available [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/makeTEgtf.pl.gz) to convert the output into a GTF that is compatible to TEtranscripts, or we can work with you to generate the GTF.
Unfortunately, at the time of this reply, I am unable to access the URL that you provided.

Thanks.

This is the usage information for the perl script:
```
 Usage: makeTEgtf.pl -c [chrom column] -s [start column] -e [stop/end column] 
                     -o [strand column] -n [source] -t [TE name column] 
                     (-f [TE family column] -C [TE class column] -1)
                     [INFILE]

 Output is printed to STDOUT

 Required parameters:
  -c [chrom column]     -    Column containing chromosome name
  -s [start column]     -    Column containing feature start position
  -e [stop/end column]  -    Column containing feature stop/end position
  -o [strand column]    -    Column containing strand information (+ or -/C)
  -t [TE name column]   -    Column containing TE name
  [INFILE]              -    File name to be processed into GTF

 Optional parameters:
  -n [source]           -    Source of the TE information 
                             (e.g. mm9_rmsk for RepeatMasker track from
                              mm9 mouse genome)
                             Defaults to "user-provided" if not specified
  -f [TE family column] -    Column containing TE family name. 
                             Defaults to TE name if not specified
  -C [TE class column]  -    Column containing TE class name. 
                             Defaults to TE family name if not specified
  -S [score column]     -    Column containing the score of the TE prediction
                             (e.g. score from RepeatMasker)
  -1                    -    Input coordinates uses 1-based indexing
                             This should be used if the input file uses
                             1-based coordinates. This should be invoked
                             if the genomic coordinates are obtained from
                             a GFF3, GTF, SAM or VCF file
                             Default: off if using BED, BAM or UCSC rmsk
                                      input files
```

**Comment by zhangaicen** [comment]
Hi Oliver,
  thanks for your quick response,  I had the TE.bed file as below:
![image](https://user-images.githubusercontent.com/67790480/128184010-ea18799c-c44c-40c1-93ff-2e82f0811ce6.png)
and use the makeTEgtf.pl I've converted it into a GTF file:
![image](https://user-images.githubusercontent.com/67790480/128184198-bfc2c2b4-11d8-40b9-8edf-fbf0c822ed3d.png)
So it is the suitable GTF file for further analysis?

best,
Thanks.

**Comment by olivertam** [comment]
Hi,

It looks quite reasonable to me. The only thing that might be annoying is that your annotations will read as follows:
`DNA/Helitron:DNA/Helitron:DNA/Helitron`
This is because the program concatenates the gene, family and class ID together. This will not break the program, but the names are just long.
Otherwise, I think it should be good to use.
Let me know if you encounter any more issues.

Thanks.

**Comment by zhangaicen** [comment]
Hi Oliver,
 I’m trying to quantify the rice TE expression using the bam file from Hisat2 with --no-mixed, as a newer of TE analysis, there are still some problems make me confused:
1. To better understand this software, I tried TEtranscript and TElocal, the software can help to build the index, but TElocal report an error ”TE annotation file needs to be a TElocal index, which will end in .locInd“， and to save time for every running, is there a method to pre-prepare .ind and .loclnd index files？
2. In the reference <DNA hypomethylation in tetraploid rice potentiates stress-responsive gene expression for salt tolerance>, I see the author display the TE expression between two samples processed by TEtranscript using boxplot, 
![图片1](https://user-images.githubusercontent.com/67790480/128321167-a64fe0f2-9016-4459-b60f-3bc3927d9386.png)
so which result coming from TEtranscript can represent TE expression like gene expression（using FPKM，CPM...)
3. In my log of transcripts, I saw very few reads were annotated as TE reads, is it reasonable or something wrong with my workflow?
![image](https://user-images.githubusercontent.com/67790480/128322327-6df8cef4-c8a3-492d-98ec-0474b84d13c0.png)

Thanks for your help.

**Comment by zhangaicen** [comment]
Hi Oliver,
I’m trying to quantify the rice TE expression using the bam file from Hisat2 with --no-mixed, as a newer of TE analysis, there are still some problems make me confused:

1. To better understand this software, I tried TEtranscript and TElocal, the software can help to build the index, but TElocal report an error ”TE annotation file needs to be a TElocal index, which will end in .locInd“， and to save time for every running, is there a method to pre-prepare .ind and .loclnd index files？

2. In the reference: DNA hypomethylation in tetraploid rice potentiates stress-responsive gene expression for salt tolerance , I see the author display the TE expression between two samples processed by TEtranscript using boxplot,
![图片1](https://user-images.githubusercontent.com/67790480/128322594-5bad36e6-4682-4a2a-bd56-9198ee4d3096.png)
so which result coming from TEtranscript can represent TE expression like gene expression（using FPKM，CPM...)

3.In my log of transcripts, I saw very few reads were annotated as TE reads, is it reasonable or something wrong with my workflow?
![image](https://user-images.githubusercontent.com/67790480/128322622-8afd6c3b-ab9c-4d0a-8fe8-5c00532a82a0.png)

Thanks for your help.

**Comment by olivertam** [comment]
Hi,

1. TElocal utilizes a different index form  (`.locInd`) than TEtranscripts (`.ind`). We can try to build the indices for you, but will need the TE GTF that you generated.
2. I am not sure which paper you are referring to, but the raw counts from TEtranscripts (`.cntTable`) can be put through differential analysis pipelines (e.g. DESeq2, which is called by TEtranscripts). You can then generate normalized counts and/or variance stabilized counts that I'm assuming were used for the plot.
3. In our analyses, we see 15-25% of our counts attributable to TE (for human). I'm not sure what the expected proportion is in rice, but it would be heavily dependent on the quality of the TE annotation.

Thanks.

**Comment by zhangaicen** [comment]
Hi，
1. Attached  is my TE GTF, please help to get the index file.
2. In their legend，they mentioned the Y-axis indicated the values of standard transcript abundance normalization by 
DESeq (default methods in TEtranscripts), so what does this refer to?
3. It has 55801 genes in rice gtf and 364081 TEs in TE gtf ,  but in the TEtranscripts (.cntTable) I found 55801 genes are all in the file, but there were only 160 TEs, and many with 0 counts,  I think this is abnormal, but can not find the reason.
![image](https://user-images.githubusercontent.com/67790480/128352660-956b6b5c-169a-4c65-97b3-b0693ac36c90.png)
[MSU.TE.withoutcentro_satelite.gtf.gz](https://github.com/mhammell-laboratory/TEtranscripts/files/6938758/MSU.TE.withoutcentro_satelite.gtf.gz)

**Comment by olivertam** [comment]
Hi,

The pre-built index for TEtranscripts is [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/prebuilt_indices/oSativaJap_MSUv7.0_noCentroSatellite_TE.gtf.ind.gz), while the pre-built index for TElocal is [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/oSativaJap_MSUv7.0_noCentroSatellite_TE.gtf.locInd.gz). They will need to be decompressed before use.

Thanks.
