### ISSUE TITLE
Index name-sorted bam files.

### ISSUE THREAD

**Issue by WeijiaSu** [mhammell-laboratory/TEtranscripts#99]
Hello,
Thanks for the useful program.  I am using bam files that are sorted by name (samtools sort -n), and the TEtranscripts showed error: [E::idx_find_and_load] Could not retrieve index file for XXX; But samtools can only index bam files sorted by position, I am wondering what kind of index file I should use for the name-sorted bam files?
Thanks for your help.
Weijia

**Comment by olivertam** [comment]
Hi Weijia,

This is a quirk of the newer Pysam module (see #82). It doesn't appear to affect the actual run of TEtranscripts. You could confirm this by looking for the output files (e.g. `xxx.cntTable`), and reading through the rest of the log once the run is done.

Thanks.
